ntoskrnl_1
ntoskrnl_2
ntoskrnl_3
ExAcquireCacheAwarePushLockExclusiveEx
ExAcquireCacheAwarePushLockSharedEx
ExAcquireFastMutex
ExAcquireFastMutexUnsafe
ExAcquirePushLockExclusiveEx
ExAcquirePushLockSharedEx
ExAcquireRundownProtection
ExAcquireRundownProtectionCacheAware
ExAcquireRundownProtectionCacheAwareEx
ExAcquireRundownProtectionEx
ExBlockOnAddressPushLock
ExBlockPushLock
ExEnterCriticalRegionAndAcquireFastMutexUnsafe
ExInitializeRundownProtection
ExInterlockedAddLargeStatistic
ExInterlockedAddUlong
ExInterlockedCompareExchange64
ExInterlockedFlushSList
ExInterlockedInsertHeadList
ExInterlockedInsertTailList
ExInterlockedPopEntryList
ExInterlockedPopEntrySList
ExInterlockedPushEntryList
ExInterlockedPushEntrySList
ExInterlockedRemoveHeadList
ExReInitializeRundownProtection
ExReInitializeRundownProtectionCacheAware
ExReleaseCacheAwarePushLockExclusiveEx
ExReleaseCacheAwarePushLockSharedEx
ExReleaseFastMutex
ExReleaseFastMutexUnsafe
ExReleaseFastMutexUnsafeAndLeaveCriticalRegion
ExReleasePushLockEx
ExReleasePushLockExclusiveEx
ExReleasePushLockSharedEx
ExReleaseResourceAndLeaveCriticalRegion
ExReleaseResourceAndLeavePriorityRegion
ExReleaseResourceLite
ExReleaseRundownProtection
ExReleaseRundownProtectionCacheAware
ExReleaseRundownProtectionCacheAwareEx
ExReleaseRundownProtectionEx
ExRundownCompleted
ExRundownCompletedCacheAware
ExTimedWaitForUnblockPushLock
ExTryAcquirePushLockExclusiveEx
ExTryAcquirePushLockSharedEx
ExTryConvertPushLockSharedToExclusiveEx
ExTryToAcquireFastMutex
ExUnblockOnAddressPushLockEx
ExUnblockPushLockEx
ExWaitForRundownProtectionRelease
ExWaitForRundownProtectionReleaseCacheAware
ExWaitForUnblockPushLock
ExfAcquirePushLockExclusive
ExfAcquirePushLockShared
ExfInterlockedAddUlong
ExfInterlockedCompareExchange64
ExfInterlockedInsertHeadList
ExfInterlockedInsertTailList
ExfInterlockedPopEntryList
ExfInterlockedPushEntryList
ExfInterlockedRemoveHeadList
ExfReleasePushLock
ExfReleasePushLockExclusive
ExfReleasePushLockShared
ExfTryAcquirePushLockShared
ExfTryToWakePushLock
ExfUnblockPushLock
Exfi386InterlockedDecrementLong
Exfi386InterlockedExchangeUlong
Exfi386InterlockedIncrementLong
ExiAcquireFastMutex
ExiReleaseFastMutex
ExiTryToAcquireFastMutex
HalExamineMBR
InterlockedCompareExchange
InterlockedDecrement
InterlockedExchange
InterlockedExchangeAdd
InterlockedIncrement
InterlockedPopEntrySList
InterlockedPushEntrySList
InterlockedPushListSList
IoGetPagingIoPriority
IoReadPartitionTable
IoSetPartitionInformation
IoWritePartitionTable
IofCallDriver
IofCompleteRequest
KeAcquireGuardedMutex
KeAcquireGuardedMutexUnsafe
KeAcquireInStackQueuedSpinLock
KeAcquireInStackQueuedSpinLockAtDpcLevel
KeAcquireInStackQueuedSpinLockForDpc
KeAcquireInStackQueuedSpinLockRaiseToSynch
KeAcquireQueuedSpinLock
KeAcquireQueuedSpinLockRaiseToSynch
KeAcquireSpinLockForDpc
KeAcquireSpinLockRaiseToSynch
KeClockInterruptNotify
KeInitializeGuardedMutex
KeInvalidateRangeAllCaches
KeReleaseGuardedMutex
KeReleaseGuardedMutexUnsafe
KeReleaseInStackQueuedSpinLock
KeReleaseInStackQueuedSpinLockForDpc
KeReleaseInStackQueuedSpinLockFromDpcLevel
KeReleaseQueuedSpinLock
KeReleaseSpinLockForDpc
KeTestSpinLock
KeTryToAcquireGuardedMutex
KeTryToAcquireQueuedSpinLock
KeTryToAcquireQueuedSpinLockRaiseToSynch
KeTryToAcquireSpinLockAtDpcLevel
KeUpdateRunTime
KeUpdateSystemTime
KefAcquireSpinLockAtDpcLevel
KefReleaseSpinLockFromDpcLevel
KfAcquireSpinLock
KfReleaseSpinLock
KiAcquireSpinLock
KiCheckForSListAddress
KiEndThreadAccountingPeriod
??arch=i386 KiEntropyQueueDpc
KiReleaseSpinLock
ObReferenceObjectSafe
ObReferenceObjectSafeWithTag
ObfDereferenceObject
ObfDereferenceObjectWithTag
ObfReferenceObject
ObfReferenceObjectWithTag
PoNotifyVSyncChange
RtlPrefetchMemoryNonTemporal
RtlUlongByteSwap
RtlUlonglongByteSwap
RtlUshortByteSwap
SeAuditingWithTokenForSubcategory
WmiGetClock
Kei386EoiHelper
AlpcGetHeaderSize
AlpcGetMessageAttribute
AlpcInitializeMessageAttribute
BgkDisplayCharacter
BgkGetConsoleState
BgkGetCursorState
BgkSetCursor
CcAddDirtyPagesToExternalCache
@ stdcall CcCanIWrite(ptr long long long)
CcCoherencyFlushAndPurgeCache
@ stdcall CcCopyRead(ptr ptr long long ptr ptr)
CcCopyReadEx
@ stdcall CcCopyWrite(ptr ptr long long ptr)
CcCopyWriteEx
CcCopyWriteWontFlush
CcDeductDirtyPagesFromExternalCache
@ stdcall CcDeferWrite(ptr ptr ptr ptr long long)
@ stdcall CcFastCopyRead(ptr long long long ptr ptr)
@ stdcall CcFastCopyWrite(ptr long long ptr)
@ extern CcFastMdlReadWait
@ stdcall CcFlushCache(ptr ptr long ptr)
CcFlushCacheToLsn
@ stdcall CcGetDirtyPages(ptr ptr ptr ptr)
@ stdcall CcGetFileObjectFromBcb(ptr)
@ stdcall CcGetFileObjectFromSectionPtrs(ptr)
CcGetFileObjectFromSectionPtrsRef
@ stdcall CcGetFlushedValidData(ptr long)
@ stdcall CcGetLsnForFileObject(ptr ptr)
@ stdcall CcInitializeCacheMap(ptr ptr long ptr ptr)
@ stdcall CcIsThereDirtyData(ptr)
CcIsThereDirtyDataEx
CcIsThereDirtyLoggedPages
@ stdcall CcMapData(ptr ptr long long ptr ptr)
@ stdcall CcMdlRead(ptr ptr long ptr ptr)
@ stdcall CcMdlReadComplete(ptr ptr)
@ stdcall CcMdlWriteAbort(ptr ptr)
@ stdcall CcMdlWriteComplete(ptr ptr ptr)
@ stdcall CcPinMappedData(ptr ptr long long ptr)
@ stdcall CcPinRead(ptr ptr long long ptr ptr)
@ stdcall CcPrepareMdlWrite(ptr ptr long ptr ptr)
@ stdcall CcPreparePinWrite(ptr ptr long long long ptr ptr)
@ stdcall CcPurgeCacheSection(ptr ptr long long)
CcRegisterExternalCache
@ stdcall CcRemapBcb(ptr)
@ stdcall CcRepinBcb(ptr)
@ stdcall CcScheduleReadAhead(ptr ptr long)
CcScheduleReadAheadEx
@ stdcall CcSetAdditionalCacheAttributes(ptr long long)
CcSetAdditionalCacheAttributesEx
@ stdcall CcSetBcbOwnerPointer(ptr ptr)
@ stdcall CcSetDirtyPageThreshold(ptr long)
@ stdcall CcSetDirtyPinnedData(ptr ptr)
@ stdcall CcSetFileSizes(ptr ptr)
CcSetFileSizesEx
@ stdcall CcSetLogHandleForFile(ptr ptr ptr)
CcSetLogHandleForFileEx
CcSetLoggedDataThreshold
CcSetParallelFlushFile
@ stdcall CcSetReadAheadGranularity(ptr long)
CcSetReadAheadGranularityEx
CcTestControl
@ stdcall CcUninitializeCacheMap(ptr ptr ptr)
CcUnmapFileOffsetFromSystemCache
@ stdcall CcUnpinData(ptr)
@ stdcall CcUnpinDataForThread(ptr ptr)
@ stdcall CcUnpinRepinnedBcb(ptr long ptr)
CcUnregisterExternalCache
@ stdcall CcWaitForCurrentLazyWriterActivity()
@ stdcall CcZeroData(ptr ptr ptr long)
CcZeroDataOnDisk
CmCallbackGetKeyObjectID
CmCallbackGetKeyObjectIDEx
CmCallbackReleaseKeyObjectIDEx
CmGetBoundTransaction
CmGetCallbackVersion
CmKeyObjectType
@ stdcall CmRegisterCallback(ptr ptr ptr)
CmRegisterCallbackEx
CmSetCallbackObjectContext
@ stdcall CmUnRegisterCallback(long long)
@ stdcall DbgBreakPoint()
@ stdcall DbgBreakPointWithStatus(long)
@ stdcall DbgCommandString(ptr ptr)
@ stdcall DbgLoadImageSymbols(ptr ptr long)
@ cdecl DbgPrint(str)
@ cdecl DbgPrintEx(long long str)
@ cdecl DbgPrintReturnControlC(str)
@ stdcall DbgPrompt(str ptr long)
@ stdcall DbgQueryDebugFilterState(long long)
@ stdcall DbgSetDebugFilterState(long long long)
DbgSetDebugPrintCallback
DbgkLkmdRegisterCallback
DbgkLkmdUnregisterCallback
EmClientQueryRuleState
EmClientRuleDeregisterNotification
EmClientRuleEvaluate
EmClientRuleRegisterNotification
EmProviderDeregister
EmProviderDeregisterEntry
EmProviderRegister
EmProviderRegisterEntry
EmpProviderRegister
EtwActivityIdControl
EtwEnableTrace
EtwEventEnabled
EtwProviderEnabled
EtwRegister
EtwRegisterClassicProvider
EtwSendTraceBuffer
EtwUnregister
EtwWrite
EtwWriteEndScenario
EtwWriteEx
EtwWriteStartScenario
EtwWriteString
EtwWriteTransfer
ExAcquireCacheAwarePushLockExclusive


@ stdcall ExAcquireResourceExclusiveLite(ptr long)
@ stdcall ExAcquireResourceSharedLite(ptr long)




@ stdcall ExAcquireSharedStarveExclusive(ptr long)
@ stdcall ExAcquireSharedWaitForExclusive(ptr long)
ExAcquireSpinLockExclusive
ExAcquireSpinLockExclusiveAtDpcLevel
ExAcquireSpinLockShared
ExAcquireSpinLockSharedAtDpcLevel
ExAllocateCacheAwarePushLock
@ stdcall ExAllocateCacheAwareRundownProtection(long long)
ExAllocateFromPagedLookasideList
@ stdcall ExAllocatePool(long long)
@ stdcall ExAllocatePoolWithQuota(long long)
@ stdcall ExAllocatePoolWithQuotaTag(long long long)
@ stdcall ExAllocatePoolWithTag(long long long)
@ stdcall ExAllocatePoolWithTagPriority(long long long long)


ExCompositionSurfaceObjectType
@ stdcall ExConvertExclusiveToSharedLite(ptr)
@ stdcall ExCreateCallback(ptr ptr long long)
ExDeleteLookasideListEx
@ stdcall ExDeleteNPagedLookasideList(ptr)
@ stdcall ExDeletePagedLookasideList(ptr)
@ stdcall ExDeleteResourceLite(ptr)
@ extern ExDesktopObjectType
@ stdcall ExDisableResourceBoostLite(ptr)

@ stdcall ExEnterCriticalRegionAndAcquireResourceExclusive(ptr)
@ stdcall ExEnterCriticalRegionAndAcquireResourceShared(ptr)
@ stdcall ExEnterCriticalRegionAndAcquireSharedWaitForExclusive(ptr)
ExEnterPriorityRegionAndAcquireResourceExclusive
ExEnterPriorityRegionAndAcquireResourceShared
@ stdcall ExEnumHandleTable(ptr ptr ptr ptr)
@ extern ExEventObjectType
@ stdcall ExExtendZone(ptr ptr long)
ExFetchLicenseData
ExFlushLookasideListEx
ExFreeCacheAwarePushLock
@ stdcall ExFreeCacheAwareRundownProtection(ptr)
@ stdcall ExFreePool(ptr)
@ stdcall ExFreePoolWithTag(ptr long)
ExFreeToPagedLookasideList
@ stdcall ExGetCurrentProcessorCounts(ptr ptr ptr)
@ stdcall ExGetCurrentProcessorCpuUsage(ptr)
@ stdcall ExGetExclusiveWaiterCount(ptr)
ExGetLicenseTamperState
@ stdcall ExGetPreviousMode()
@ stdcall ExGetSharedWaiterCount(ptr)
ExInitializeLookasideListEx
@ stdcall ExInitializeNPagedLookasideList(ptr ptr ptr long long long long)
@ stdcall ExInitializePagedLookasideList(ptr ptr ptr long long long long)
ExInitializePushLock
@ stdcall ExInitializeResourceLite(ptr)

@ stdcall ExInitializeRundownProtectionCacheAware(ptr long)
@ stdcall ExInitializeZone(ptr long ptr long)
@ stdcall ExInterlockedAddLargeInteger(ptr long long ptr)

ExInterlockedDecrementLong
ExInterlockedExchangeUlong
@ stdcall ExInterlockedExtendZone(ptr ptr long ptr)





-arch=i386 ExInterlockedIncrementLong
@ stdcall ExIsProcessorFeaturePresent(long)
@ stdcall ExIsResourceAcquiredExclusiveLite(ptr)
@ stdcall ExIsResourceAcquiredSharedLite(ptr)
@ stdcall ExLocalTimeToSystemTime(ptr ptr)
ExNotifyBootDeviceRemoval
@ stdcall ExNotifyCallback(ptr ptr ptr)
ExQueryAttributeInformation
@ stdcall -arch=x86_64 ExQueryDepthSList(ptr)
ExQueryFastCacheDevLicense
@ stdcall ExQueryPoolBlockSize(ptr ptr)
ExQueryTimerResolution
ExQueryWnfStateData
@ stdcall ExQueueWorkItem(ptr long)
@ stdcall ExRaiseAccessViolation()
@ stdcall ExRaiseDatatypeMisalignment()
@ stdcall ExRaiseException(ptr) RtlRaiseException
@ stdcall ExRaiseHardError(long long long ptr long ptr)
@ stdcall ExRaiseStatus(long) RtlRaiseStatus


ExRegisterAttributeInformationCallback
ExRegisterBootDevice
@ stdcall ExRegisterCallback(ptr ptr ptr)
ExRegisterExtension
@ stdcall ExReinitializeResourceLite(ptr)
ExReleaseCacheAwarePushLockExclusive





@ stdcall ExReleaseResourceForThreadLite(ptr long)





ExReleaseSpinLockExclusive
ExReleaseSpinLockExclusiveFromDpcLevel
ExReleaseSpinLockShared
ExReleaseSpinLockSharedFromDpcLevel


@ extern ExSemaphoreObjectType
ExSetLicenseTamperState
@ stdcall ExSetResourceOwnerPointer(ptr ptr)
ExSetResourceOwnerPointerEx
@ stdcall ExSetTimerResolution(long long)
@ stdcall ExSizeOfRundownProtectionCacheAware()
ExSubscribeWnfStateChange
@ stdcall ExSystemExceptionFilter()
@ stdcall ExSystemTimeToLocalTime(ptr ptr)

ExTryConvertSharedSpinLockExclusive
ExTryQueueWorkItem

ExUnregisterAttributeInformationCallback
@ stdcall ExUnregisterCallback(ptr)
ExUnregisterExtension
ExUnsubscribeWnfStateChange
ExUpdateLicenseData
@ stdcall ExUuidCreate(ptr)
@ stdcall ExVerifySuite(long)



@ extern ExWindowStationObjectType








-arch=i386 Exi386InterlockedDecrementLong
-arch=i386 Exi386InterlockedExchangeUlong
-arch=i386 Exi386InterlockedIncrementLong
@ stdcall -arch=x86_64 ExpInterlockedFlushSList(ptr)
@ stdcall -arch=x86_64 ExpInterlockedPopEntrySList(ptr ptr)
@ stdcall -arch=x86_64 ExpInterlockedPushEntrySList(ptr ptr)
FirstEntrySList
FsRtlAcknowledgeEcp
@ stdcall FsRtlAcquireFileExclusive(ptr)
@ stdcall FsRtlAddBaseMcbEntry(ptr long long long long long long)
FsRtlAddBaseMcbEntryEx
@ stdcall FsRtlAddLargeMcbEntry(ptr long long long long long long)
@ stdcall FsRtlAddMcbEntry(ptr long long long)
@ stdcall FsRtlAddToTunnelCache(ptr long long ptr ptr long long ptr)
FsRtlAllocateExtraCreateParameter
FsRtlAllocateExtraCreateParameterFromLookasideList
FsRtlAllocateExtraCreateParameterList
@ stdcall FsRtlAllocateFileLock(ptr ptr)
@ stdcall FsRtlAllocatePool(long long)
@ stdcall FsRtlAllocatePoolWithQuota(long long)
@ stdcall FsRtlAllocatePoolWithQuotaTag(long long long)
@ stdcall FsRtlAllocatePoolWithTag(long long long)
@ stdcall FsRtlAllocateResource()
@ stdcall FsRtlAreNamesEqual(ptr ptr long wstr)
FsRtlAreThereCurrentOrInProgressFileLocks
FsRtlAreThereWaitingFileLocks
FsRtlAreVolumeStartupApplicationsComplete
@ stdcall FsRtlBalanceReads(ptr)
FsRtlCancellableWaitForMultipleObjects
FsRtlCancellableWaitForSingleObject
FsRtlChangeBackingFileObject
FsRtlCheckLockForOplockRequest
@ stdcall FsRtlCheckLockForReadAccess(ptr ptr)
@ stdcall FsRtlCheckLockForWriteAccess(ptr ptr)
@ stdcall FsRtlCheckOplock(ptr ptr ptr ptr ptr)
FsRtlCheckOplockEx
@ stdcall FsRtlCopyRead(ptr ptr long long long ptr ptr ptr)
@ stdcall FsRtlCopyWrite(ptr ptr long long long ptr ptr ptr)
@ stdcall FsRtlCreateSectionForDataScan(ptr ptr ptr ptr long ptr ptr long long long)
@ stdcall FsRtlCurrentBatchOplock(ptr)
FsRtlCurrentOplock
FsRtlCurrentOplockH
FsRtlDeleteExtraCreateParameterLookasideList
@ stdcall FsRtlDeleteKeyFromTunnelCache(ptr long long)
@ stdcall FsRtlDeleteTunnelCache(ptr)
@ stdcall FsRtlDeregisterUncProvider(ptr)
@ stdcall FsRtlDissectDbcs(long ptr ptr ptr)
@ stdcall FsRtlDissectName(long ptr ptr ptr)
@ stdcall FsRtlDoesDbcsContainWildCards(ptr)
@ stdcall FsRtlDoesNameContainWildCards(ptr)
@ stdcall FsRtlFastCheckLockForRead(ptr ptr ptr long ptr ptr)
@ stdcall FsRtlFastCheckLockForWrite(ptr ptr ptr long ptr ptr)
@ stdcall FsRtlFastUnlockAll(ptr ptr ptr ptr)
@ stdcall FsRtlFastUnlockAllByKey(ptr ptr ptr long ptr)
@ stdcall FsRtlFastUnlockSingle(ptr ptr ptr ptr ptr long ptr long)
FsRtlFindExtraCreateParameter
@ stdcall FsRtlFindInTunnelCache(ptr long long ptr ptr ptr ptr ptr)
FsRtlFreeExtraCreateParameter
FsRtlFreeExtraCreateParameterList
@ stdcall FsRtlFreeFileLock(ptr)
FsRtlGetEcpListFromIrp
@ stdcall FsRtlGetFileSize(ptr ptr)
@ stdcall FsRtlGetNextBaseMcbEntry(ptr long ptr ptr ptr)
FsRtlGetNextExtraCreateParameter
@ stdcall FsRtlGetNextFileLock(ptr long)
@ stdcall FsRtlGetNextLargeMcbEntry(ptr long ptr ptr ptr)
@ stdcall FsRtlGetNextMcbEntry(ptr long ptr ptr ptr)
FsRtlGetSectorSizeInformation
FsRtlGetSupportedFeatures
FsRtlGetVirtualDiskNestingLevel
FsRtlIncrementCcFastMdlReadWait
@ stdcall FsRtlIncrementCcFastReadNoWait()
@ stdcall FsRtlIncrementCcFastReadNotPossible()
@ stdcall FsRtlIncrementCcFastReadResourceMiss()
@ stdcall FsRtlIncrementCcFastReadWait()
FsRtlInitExtraCreateParameterLookasideList
@ stdcall FsRtlInitializeBaseMcb(ptr ptr)
FsRtlInitializeBaseMcbEx
FsRtlInitializeExtraCreateParameter
FsRtlInitializeExtraCreateParameterList
FsRtlInitializeFileLock
FsRtlInitializeLargeMcb
FsRtlInitializeMcb
FsRtlInitializeOplock
FsRtlInitializeTunnelCache
FsRtlInsertExtraCreateParameter
FsRtlInsertPerFileContext
FsRtlInsertPerFileObjectContext
FsRtlInsertPerStreamContext
FsRtlIsDbcsInExpression
FsRtlIsEcpAcknowledged
FsRtlIsEcpFromUserMode
FsRtlIsFatDbcsLegal
FsRtlIsHpfsDbcsLegal
FsRtlIsNameInExpression
FsRtlIsNtstatusExpected
FsRtlIsPagingFile
FsRtlIsSystemPagingFile
FsRtlIsTotalDeviceFailure
FsRtlIssueDeviceIoControl
FsRtlLegalAnsiCharacterArray
FsRtlLogCcFlushError
FsRtlLookupBaseMcbEntry
FsRtlLookupLargeMcbEntry
FsRtlLookupLastBaseMcbEntry
FsRtlLookupLastBaseMcbEntryAndIndex
FsRtlLookupLastLargeMcbEntry
FsRtlLookupLastLargeMcbEntryAndIndex
FsRtlLookupLastMcbEntry
FsRtlLookupMcbEntry
FsRtlLookupPerFileContext
FsRtlLookupPerFileObjectContext
FsRtlLookupPerStreamContextInternal
FsRtlMdlRead
FsRtlMdlReadComplete
FsRtlMdlReadCompleteDev
FsRtlMdlReadDev
FsRtlMdlWriteComplete
FsRtlMdlWriteCompleteDev
FsRtlMupGetProviderIdFromName
FsRtlMupGetProviderInfoFromFileObject
FsRtlNormalizeNtstatus
FsRtlNotifyChangeDirectory
FsRtlNotifyCleanup
FsRtlNotifyCleanupAll
FsRtlNotifyFilterChangeDirectory
FsRtlNotifyFilterReportChange
FsRtlNotifyFullChangeDirectory
FsRtlNotifyFullReportChange
FsRtlNotifyInitializeSync
FsRtlNotifyReportChange
FsRtlNotifyUninitializeSync
FsRtlNotifyVolumeEvent
FsRtlNotifyVolumeEventEx
FsRtlNumberOfRunsInBaseMcb
FsRtlNumberOfRunsInLargeMcb
FsRtlNumberOfRunsInMcb
FsRtlOplockBreakH
FsRtlOplockBreakToNone
FsRtlOplockBreakToNoneEx
FsRtlOplockFsctrl
FsRtlOplockFsctrlEx
FsRtlOplockIsFastIoPossible
FsRtlOplockIsSharedRequest
FsRtlOplockKeysEqual
FsRtlPostPagingFileStackOverflow
FsRtlPostStackOverflow
FsRtlPrepareMdlWrite
FsRtlPrepareMdlWriteDev
FsRtlPrepareToReuseEcp
FsRtlPrivateLock
FsRtlProcessFileLock
FsRtlQueryMaximumVirtualDiskNestingLevel
FsRtlRegisterFileSystemFilterCallbacks
FsRtlRegisterFltMgrCalls
FsRtlRegisterMupCalls
FsRtlRegisterUncProvider
FsRtlRegisterUncProviderEx
FsRtlReleaseFile
FsRtlRemoveBaseMcbEntry
FsRtlRemoveDotsFromPath
FsRtlRemoveExtraCreateParameter
FsRtlRemoveLargeMcbEntry
FsRtlRemoveMcbEntry
FsRtlRemovePerFileContext
FsRtlRemovePerFileObjectContext
FsRtlRemovePerStreamContext
FsRtlResetBaseMcb
FsRtlResetLargeMcb
FsRtlSetEcpListIntoIrp
FsRtlSplitBaseMcb
FsRtlSplitLargeMcb
FsRtlSyncVolumes
FsRtlTeardownPerFileContexts
FsRtlTeardownPerStreamContexts
FsRtlTruncateBaseMcb
FsRtlTruncateLargeMcb
FsRtlTruncateMcb
FsRtlUninitializeBaseMcb
FsRtlUninitializeFileLock
FsRtlUninitializeLargeMcb
FsRtlUninitializeMcb
FsRtlUninitializeOplock
FsRtlValidateReparsePointBuffer
HalDispatchTable

HalPrivateDispatchTable
HeadlessDispatch
HvlGetLpIndexFromApicId
-arch=x86_64 HvlPerformEndOfInterrupt
HvlQueryActiveHypervisorProcessorCount
HvlQueryActiveProcessors
HvlQueryConnection
HvlQueryHypervisorProcessorNodeNumber
HvlQueryProcessorTopology
HvlQueryProcessorTopologyCount
HvlQueryProcessorTopologyHighestId
HvlRegisterInterruptCallback
HvlRegisterWheaErrorNotification
HvlUnregisterInterruptCallback
HvlUnregisterWheaErrorNotification
InbvAcquireDisplayOwnership
InbvCheckDisplayOwnership
InbvDisplayString
InbvEnableBootDriver
InbvEnableDisplayString
InbvInstallDisplayStringFilter
InbvIsBootDriverInstalled
InbvNotifyDisplayOwnershipChange
InbvNotifyDisplayOwnershipLost
InbvResetDisplay
InbvSetScrollRegion
InbvSetTextColor
InbvSolidColorFill
InitSafeBootMode
-arch=x86_64 InitializeSListHead
IoAcquireCancelSpinLock
IoAcquireRemoveLockEx
IoAcquireVpbSpinLock
IoAdapterObjectType
IoAdjustStackSizeForRedirection
IoAllocateAdapterChannel
IoAllocateController
IoAllocateDriverObjectExtension
IoAllocateErrorLogEntry
IoAllocateIrp
IoAllocateMdl
IoAllocateMiniCompletionPacket
IoAllocateSfioStreamIdentifier
IoAllocateWorkItem
IoApplyPriorityInfoThread
IoAssignResources
IoAttachDevice
IoAttachDeviceByPointer
IoAttachDeviceToDeviceStack
IoAttachDeviceToDeviceStackSafe
IoBuildAsynchronousFsdRequest
IoBuildDeviceIoControlRequest
IoBuildPartialMdl
IoBuildSynchronousFsdRequest
IoCallDriver
IoCancelFileOpen
IoCancelIrp
IoCheckDesiredAccess
IoCheckEaBufferValidity
IoCheckFunctionAccess
IoCheckQuerySetFileInformation
IoCheckQuerySetVolumeInformation
IoCheckQuotaBufferValidity
IoCheckShareAccess
IoCheckShareAccessEx
IoClearActivityIdThread
IoClearDependency
IoClearIrpExtraCreateParameter
IoClearReservedDependency
IoCompleteRequest
IoConnectInterrupt
IoConnectInterruptEx
IoCopyDeviceObjectHint
IoCreateArcName
IoCreateController
IoCreateDevice
IoCreateDisk
IoCreateDriver
IoCreateFile
IoCreateFileEx
IoCreateFileSpecifyDeviceObjectHint
IoCreateNotificationEvent
IoCreateStreamFileObject
IoCreateStreamFileObjectEx
IoCreateStreamFileObjectLite
IoCreateSymbolicLink
IoCreateSynchronizationEvent
IoCreateSystemThread
IoCreateUnprotectedSymbolicLink
IoCsqInitialize
IoCsqInitializeEx
IoCsqInsertIrp
IoCsqInsertIrpEx
IoCsqRemoveIrp
IoCsqRemoveNextIrp
IoDecrementKeepAliveCount
IoDeleteAllDependencyRelations
IoDeleteController
IoDeleteDevice
IoDeleteDriver
IoDeleteSymbolicLink
IoDetachDevice
IoDeviceHandlerObjectSize
IoDeviceHandlerObjectType
IoDeviceObjectType
IoDisconnectInterrupt
IoDisconnectInterruptEx
IoDriverObjectType
IoDuplicateDependency
IoEnqueueIrp
IoEnumerateDeviceObjectList
IoEnumerateRegisteredFiltersList
IoFastQueryNetworkAttributes
IoFileObjectType
IoForwardAndCatchIrp
IoForwardIrpSynchronously
IoFreeController
IoFreeErrorLogEntry
IoFreeIrp
IoFreeMdl
IoFreeMiniCompletionPacket
IoFreeSfioStreamIdentifier
IoFreeWorkItem
IoGetActivityIdIrp
IoGetActivityIdThread
IoGetAffinityInterrupt
IoGetAttachedDevice
IoGetAttachedDeviceReference
IoGetBaseFileSystemDeviceObject
IoGetBootDiskInformation
IoGetBootDiskInformationLite
IoGetConfigurationInformation
IoGetContainerInformation
IoGetCurrentProcess
IoGetDeviceAttachmentBaseRef
IoGetDeviceInterfaceAlias
IoGetDeviceInterfacePropertyData
IoGetDeviceInterfaces
IoGetDeviceNumaNode
IoGetDeviceObjectPointer
IoGetDeviceProperty
IoGetDevicePropertyData
IoGetDeviceToVerify
IoGetDiskDeviceObject
IoGetDmaAdapter
IoGetDriverObjectExtension
IoGetFileObjectGenericMapping
IoGetInitialStack
IoGetInitiatorProcess
IoGetIoPriorityHint
IoGetIrpExtraCreateParameter
IoGetLowerDeviceObject
IoGetOplockKeyContext
IoGetOplockKeyContextEx

IoGetRelatedDeviceObject
IoGetRequestorProcess
IoGetRequestorProcessId
IoGetRequestorSessionId
IoGetSfioStreamIdentifier
IoGetStackLimits
IoGetSymlinkSupportInformation
IoGetTopLevelIrp
IoGetTransactionParameterBlock
IoIncrementKeepAliveCount
IoInitializeIrp
IoInitializeMiniCompletionPacket
IoInitializeRemoveLockEx
IoInitializeTimer
IoInitializeWorkItem
IoInvalidateDeviceRelations
IoInvalidateDeviceState
-arch=x86_64 IoIs32bitProcess
IoIsFileObjectIgnoringSharing
IoIsFileOriginRemote
IoIsOperationSynchronous
IoIsSystemThread
IoIsValidIrpStatus
IoIsValidNameGraftingBuffer
IoIsWdmVersionAvailable
IoMakeAssociatedIrp
IoOpenDeviceInterfaceRegistryKey
IoOpenDeviceRegistryKey
IoPageRead
IoPropagateActivityIdToThread
IoQueryDeviceDescription
IoQueryFileDosDeviceName
IoQueryFileInformation
IoQueryVolumeInformation
IoQueueThreadIrp
IoQueueWorkItem
IoQueueWorkItemEx
IoRaiseHardError
IoRaiseInformationalHardError
IoReadDiskSignature
IoReadOperationCount

IoReadPartitionTableEx
IoReadTransferCount
IoRegisterBootDriverCallback
IoRegisterBootDriverReinitialization
IoRegisterContainerNotification
IoRegisterDeviceInterface
IoRegisterDriverReinitialization
IoRegisterFileSystem
IoRegisterFsRegistrationChange
IoRegisterFsRegistrationChangeMountAware
IoRegisterLastChanceShutdownNotification
IoRegisterPlugPlayNotification
IoRegisterPriorityCallback
IoRegisterShutdownNotification
IoReleaseCancelSpinLock
IoReleaseRemoveLockAndWaitEx
IoReleaseRemoveLockEx
IoReleaseVpbSpinLock
IoRemoveShareAccess
IoReplaceFileObjectName
IoReplacePartitionUnit
IoReportDetectedDevice
IoReportHalResourceUsage
IoReportInterruptActive
IoReportInterruptInactive
IoReportResourceForDetection
IoReportResourceUsage
IoReportRootDevice
IoReportTargetDeviceChange
IoReportTargetDeviceChangeAsynchronous
IoRequestDeviceEject
IoRequestDeviceEjectEx
IoReserveDependency
IoResolveDependency
IoRetrievePriorityInfo
IoReuseIrp
IoSetActivityIdIrp
IoSetActivityIdThread
IoSetCompletionRoutineEx
IoSetDependency
IoSetDeviceInterfacePropertyData
IoSetDeviceInterfaceState
IoSetDevicePropertyData
IoSetDeviceToVerify
IoSetFileObjectIgnoreSharing
IoSetFileOrigin
IoSetHardErrorOrVerifyDevice
IoSetInformation
IoSetIoCompletion
IoSetIoCompletionEx
IoSetIoPriorityHint
IoSetIoPriorityHintIntoFileObject
IoSetIoPriorityHintIntoThread
IoSetIrpExtraCreateParameter

IoSetPartitionInformationEx
IoSetShareAccess
IoSetShareAccessEx
IoSetStartIoAttributes
IoSetSystemPartition
IoSetThreadHardErrorMode
IoSetTopLevelIrp
IoSizeofWorkItem
IoStartNextPacket
IoStartNextPacketByKey
IoStartPacket
IoStartTimer
IoStatisticsLock
IoStopTimer
IoSynchronousCallDriver
IoSynchronousInvalidateDeviceRelations
IoSynchronousPageWrite
IoThreadToProcess
IoTransferActivityId
IoTranslateBusAddress
IoTryQueueWorkItem
IoUninitializeWorkItem
IoUnregisterBootDriverCallback
IoUnregisterContainerNotification
IoUnregisterFileSystem
IoUnregisterFsRegistrationChange
IoUnregisterPlugPlayNotification
IoUnregisterPlugPlayNotificationEx
IoUnregisterPriorityCallback
IoUnregisterShutdownNotification
IoUpdateShareAccess
IoValidateDeviceIoControlAccess
IoVerifyPartitionTable
IoVerifyVolume
IoVolumeDeviceToDosName
IoVolumeDeviceToGuid
IoVolumeDeviceToGuidPath
IoWMIAllocateInstanceIds
IoWMIDeviceObjectToInstanceName
arch=x86_64 IoWMIDeviceObjectToProviderId
IoWMIExecuteMethod
IoWMIHandleToInstanceName
IoWMIOpenBlock
IoWMIQueryAllData
IoWMIQueryAllDataMultiple
IoWMIQuerySingleInstance
IoWMIQuerySingleInstanceMultiple
IoWMIRegistrationControl
IoWMISetNotificationCallback
IoWMISetSingleInstance
IoWMISetSingleItem
IoWMISuggestInstanceName
IoWMIWriteEvent
IoWithinStackLimits
IoWriteErrorLogEntry
IoWriteOperationCount

IoWritePartitionTableEx
IoWriteTransferCount


KdChangeOption
KdDebuggerEnabled
KdDebuggerNotPresent
KdDisableDebugger
KdEnableDebugger
KdEnteredDebugger
KdLogDbgPrint
KdPollBreakIn
KdPowerTransition
KdRefreshDebuggerNotPresent
KdSystemDebugControl






arch=i386 Ke386IoSetAccessProcess
arch=i386 Ke386QueryIoAccessMap
arch=i386 Ke386SetIoAccessMap
KeAcquireInterruptSpinLock


arch=i386 KeAcquireSpinLock
KeAcquireSpinLockAtDpcLevel

arch=x86_64 KeAcquireSpinLockRaiseToDpc

KeAddGroupAffinityEx
KeAddProcessorAffinityEx
KeAddProcessorGroupAffinity
KeAddSystemServiceTable
KeAlertThread
KeAllocateCalloutStack
KeAllocateCalloutStackEx
KeAndAffinityEx
KeAndGroupAffinityEx
KeAreAllApcsDisabled
KeAreApcsDisabled
KeAttachProcess
KeBugCheck
KeBugCheckEx
KeCancelTimer
KeCapturePersistentThreadState
KeCheckProcessorAffinityEx
KeCheckProcessorGroupAffinity
KeClearEvent
KeComplementAffinityEx
KeCopyAffinityEx
KeCountSetBitsAffinityEx
KeCountSetBitsGroupAffinity
KeDelayExecutionThread
KeDeregisterBugCheckCallback
KeDeregisterBugCheckReasonCallback
KeDeregisterNmiCallback
KeDeregisterProcessorChangeCallback
KeDetachProcess
KeDispatchSecondaryInterrupt
KeEnterCriticalRegion
KeEnterGuardedRegion
KeEnterKernelDebugger
KeEnumerateNextProcessor
KeExpandKernelStackAndCallout
KeExpandKernelStackAndCalloutEx
KeFindConfigurationEntry
KeFindConfigurationNextEntry
KeFindFirstSetLeftAffinityEx
KeFindFirstSetLeftGroupAffinity
KeFindFirstSetRightGroupAffinity
KeFirstGroupAffinityEx
KeFlushEntireTb
KeFlushQueuedDpcs
KeFreeCalloutStack
KeGenericCallDpc
arch=x86_64 KeGetCurrentIrql
KeGetCurrentNodeNumber
KeGetCurrentProcessorNumberEx
KeGetCurrentThread
KeGetNextTimerExpirationDueTime
arch=i386 KeGetPreviousMode
KeGetProcessorIndexFromNumber
KeGetProcessorNumberFromIndex
KeGetRecommendedSharedDataAlignment
KeGetXSaveFeatureFlags
KeHwPolicyLocateResource
arch=i386 KeI386MachineType
KeInitializeAffinityEx
KeInitializeApc
KeInitializeCrashDumpHeader
KeInitializeDeviceQueue
KeInitializeDpc
KeInitializeEnumerationContext
KeInitializeEnumerationContextFromGroup
KeInitializeEvent

KeInitializeInterrupt
KeInitializeMutant
KeInitializeMutex
KeInitializeQueue
KeInitializeSecondaryInterruptServices
KeInitializeSemaphore
KeInitializeSpinLock
KeInitializeThreadedDpc
KeInitializeTimer
KeInitializeTimerEx
KeInsertByKeyDeviceQueue
KeInsertDeviceQueue
KeInsertHeadQueue
KeInsertQueue
KeInsertQueueApc
KeInsertQueueDpc
KeInterlockedClearProcessorAffinityEx
KeInterlockedSetProcessorAffinityEx
KeInvalidateAllCaches

KeIpiGenericCall
KeIsAttachedProcess
KeIsEmptyAffinityEx
KeIsEqualAffinityEx
KeIsExecutingDpc
KeIsSingleGroupAffinityEx
KeIsSubsetAffinityEx
KeIsWaitListEmpty
arch=x86_64 KeLastBranchMSR
KeLeaveCriticalRegion
KeLeaveGuardedRegion
KeLoaderBlock
arch=x86_64 KeLowerIrql
KeNumberProcessors
KeOrAffinityEx
arch=i386 KePollFreezeExecution
KeProcessorGroupAffinity
KeProfileInterruptWithSource
KePulseEvent
KeQueryActiveGroupCount
KeQueryActiveProcessorAffinity
KeQueryActiveProcessorCount
KeQueryActiveProcessorCountEx
KeQueryActiveProcessors
KeQueryDpcWatchdogInformation
KeQueryGroupAffinity
KeQueryGroupAffinityEx
KeQueryHardwareCounterConfiguration
KeQueryHighestNodeNumber
arch=i386 KeQueryInterruptTime
KeQueryLogicalProcessorRelationship
KeQueryMaximumGroupCount
KeQueryMaximumProcessorCount
KeQueryMaximumProcessorCountEx
KeQueryNodeActiveAffinity
KeQueryNodeMaximumProcessorCount
arch=x86_64 KeQueryPrcbAddress
KeQueryPriorityThread
KeQueryRuntimeThread
arch=i386 KeQuerySystemTime
KeQuerySystemTimePrecise
arch=i386 KeQueryTickCount
KeQueryTimeIncrement
KeQueryTotalCycleTimeProcess
KeQueryTotalCycleTimeThread
KeQueryUnbiasedInterruptTime
arch=x86_64 KeRaiseIrqlToDpcLevel
KeRaiseUserException
KeReadStateEvent
KeReadStateMutant
KeReadStateMutex
KeReadStateQueue
KeReadStateSemaphore
KeReadStateTimer
KeRegisterBugCheckCallback
KeRegisterBugCheckReasonCallback
KeRegisterNmiCallback
KeRegisterProcessorChangeCallback





KeReleaseInterruptSpinLock
KeReleaseMutant
KeReleaseMutex

KeReleaseSemaphore
KeReleaseSpinLock

KeReleaseSpinLockFromDpcLevel
KeRemoveByKeyDeviceQueue
KeRemoveByKeyDeviceQueueIfBusy
KeRemoveDeviceQueue
KeRemoveEntryDeviceQueue
KeRemoveGroupAffinityEx
KeRemoveProcessorAffinityEx
KeRemoveProcessorGroupAffinity
KeRemoveQueue
KeRemoveQueueDpc
KeRemoveQueueEx
KeRemoveSystemServiceTable
KeResetEvent
KeRestoreExtendedProcessorState
KeRestoreFloatingPointState
KeRevertToUserAffinityThread
KeRevertToUserAffinityThreadEx
KeRevertToUserGroupAffinityThread
KeRundownQueue
KeSaveExtendedProcessorState
KeSaveFloatingPointState
KeSaveStateForHibernate
arch=i386 KeServiceDescriptorTable
KeSetActualBasePriorityThread
KeSetAffinityThread
KeSetBasePriorityThread
KeSetCoalescableTimer
KeSetDmaIoCoherency
KeSetEvent
KeSetEventBoostPriority
KeSetHardwareCounterConfiguration
KeSetIdealProcessorThread
KeSetImportanceDpc
KeSetKernelStackSwapEnable
KeSetPriorityThread
KeSetProfileIrql
KeSetSystemAffinityThread
KeSetSystemAffinityThreadEx
KeSetSystemGroupAffinityThread
KeSetTargetProcessorDpc
KeSetTargetProcessorDpcEx
KeSetTimeIncrement
KeSetTimer
KeSetTimerEx
KeSignalCallDpcDone
KeSignalCallDpcSynchronize
KeStackAttachProcess
KeStartDynamicProcessor
KeSubtractAffinityEx
KeSweepLocalCaches
KeSynchronizeExecution
KeTestAlertThread

arch=i386 KeTickCount



KeUnstackDetachProcess


KeUpdateSystemTimeAssist
KeUserModeCallback
KeWaitForMultipleObjects
KeWaitForMutexObject
KeWaitForSingleObject
arch=x86_64 KfRaiseIrql
KiBugCheckData
KiCheckForKernelApcDelivery
arch=i386 KiCoprocessorError
KiCpuId
arch=i386 KiDeliverApc
arch=i386 KiDispatchInterrupt
arch=i386 KiEntropyQueueDpc
arch=i386 KiIpiServiceRoutine
arch=i386 KiUnexpectedInterrupt
KseQueryDeviceData
KseQueryDeviceDataList
KseQueryDeviceFlags
KseRegisterShim
KseUnregisterShim
LdrAccessResource
LdrEnumResources
LdrFindResourceDirectory_U
LdrFindResourceEx_U
LdrFindResource_U
LdrResFindResource
LdrResFindResourceDirectory
LdrResSearchResource
LpcPortObjectType
LpcReplyWaitReplyPort
LpcRequestPort
LpcRequestWaitReplyPort
LpcRequestWaitReplyPortEx
LpcSendWaitReceivePort
LsaCallAuthenticationPackage
LsaDeregisterLogonProcess
LsaFreeReturnBuffer
LsaLogonUser
LsaLookupAuthenticationPackage
LsaRegisterLogonProcess
Mm64BitPhysicalAddress
MmAddPhysicalMemory
MmAddVerifierThunks
MmAdjustWorkingSetSize
MmAdvanceMdl
MmAllocateContiguousMemory
MmAllocateContiguousMemorySpecifyCache
MmAllocateContiguousMemorySpecifyCacheNode
MmAllocateContiguousNodeMemory
MmAllocateMappingAddress
MmAllocateNodePagesForMdlEx
MmAllocateNonCachedMemory
MmAllocatePagesForMdl
MmAllocatePagesForMdlEx
MmBadPointer
MmBuildMdlForNonPagedPool
MmCanFileBeTruncated
MmCommitSessionMappedView
MmCopyVirtualMemory
MmCreateMdl
MmCreateMirror
MmCreateSection
MmDisableModifiedWriteOfSection
MmDoesFileHaveUserWritableReferences
MmFlushImageSection
MmForceSectionClosed
MmFreeContiguousMemory
MmFreeContiguousMemorySpecifyCache
MmFreeMappingAddress
MmFreeNonCachedMemory
MmFreePagesFromMdl
MmGetPhysicalAddress
MmGetPhysicalMemoryRanges
MmGetSystemRoutineAddress
MmGetVirtualForPhysical
MmGrowKernelStack
MmHighestUserAddress
MmIsAddressValid
MmIsDriverSuspectForVerifier
MmIsDriverVerifying
MmIsDriverVerifyingByAddress
MmIsIoSpaceActive
MmIsNonPagedSystemAddressValid
MmIsRecursiveIoFault
MmIsThisAnNtAsSystem
MmIsVerifierEnabled
MmLockPagableDataSection
MmLockPagableImageSection
MmLockPagableSectionByHandle
MmMapIoSpace
MmMapLockedPages
MmMapLockedPagesSpecifyCache
MmMapLockedPagesWithReservedMapping
MmMapMemoryDumpMdl
MmMapUserAddressesToPage
MmMapVideoDisplay
MmMapViewInSessionSpace
MmMapViewInSystemSpace
MmMapViewOfSection
MmMarkPhysicalMemoryAsBad
MmMarkPhysicalMemoryAsGood
MmPageEntireDriver
MmPrefetchPages
MmPrefetchVirtualAddresses
MmProbeAndLockPages
MmProbeAndLockProcessPages
MmProbeAndLockSelectedPages
MmProtectMdlSystemAddress
MmQuerySystemSize
MmRemovePhysicalMemory
MmResetDriverPaging
MmRotatePhysicalView
MmSectionObjectType
MmSecureVirtualMemory
MmSetAddressRangeModified
MmSetBankedSection
MmSizeOfMdl
MmSystemRangeStart
MmTrimAllSystemPagableMemory
MmUnlockPagableImageSection
MmUnlockPages
MmUnmapIoSpace
MmUnmapLockedPages
MmUnmapReservedMapping
MmUnmapVideoDisplay
MmUnmapViewInSessionSpace
MmUnmapViewInSystemSpace
MmUnmapViewOfSection
MmUnsecureVirtualMemory
MmUserProbeAddress
NlsAnsiCodePage
NlsLeadByteInfo
NlsMbCodePageTag
NlsMbOemCodePageTag
NlsOemCodePage
NlsOemLeadByteInfo
NtAddAtom
NtAdjustPrivilegesToken
NtAllocateLocallyUniqueId
NtAllocateUuids
NtAllocateVirtualMemory
NtBuildGUID
NtBuildLab
NtBuildNumber
NtClose
NtCommitComplete
NtCommitEnlistment
NtCommitTransaction
NtConnectPort
NtCreateEnlistment
NtCreateEvent
NtCreateFile
NtCreateResourceManager
NtCreateSection
NtCreateTransaction
NtCreateTransactionManager
NtDeleteAtom
NtDeleteFile
NtDeviceIoControlFile
NtDuplicateObject
NtDuplicateToken
NtEnumerateTransactionObject
NtFindAtom
NtFreeVirtualMemory
NtFreezeTransactions
NtFsControlFile
NtGetEnvironmentVariableEx
NtGetNotificationResourceManager
NtGlobalFlag
NtLockFile
NtMakePermanentObject
NtMapViewOfSection
NtNotifyChangeDirectoryFile
NtOpenEnlistment
NtOpenFile
NtOpenProcess
NtOpenProcessToken
NtOpenProcessTokenEx
NtOpenResourceManager
NtOpenThread
NtOpenThreadToken
NtOpenThreadTokenEx
NtOpenTransaction
NtOpenTransactionManager
NtPrePrepareComplete
NtPrePrepareEnlistment
NtPrepareComplete
NtPrepareEnlistment
NtPropagationComplete
NtPropagationFailed
NtQueryDirectoryFile
NtQueryEaFile
NtQueryEnvironmentVariableInfoEx
NtQueryInformationAtom
NtQueryInformationEnlistment
NtQueryInformationFile
NtQueryInformationProcess
NtQueryInformationResourceManager
NtQueryInformationThread
NtQueryInformationToken
NtQueryInformationTransaction
NtQueryInformationTransactionManager
NtQueryQuotaInformationFile
NtQuerySecurityAttributesToken
NtQuerySecurityObject
NtQuerySystemInformation
NtQuerySystemInformationEx
NtQueryVolumeInformationFile
NtReadFile
NtReadOnlyEnlistment
NtRecoverEnlistment
NtRecoverResourceManager
NtRecoverTransactionManager
NtRequestPort
NtRequestWaitReplyPort
NtRollbackComplete
NtRollbackEnlistment
NtRollbackTransaction
NtSetEaFile
NtSetEvent
NtSetInformationEnlistment
NtSetInformationFile
NtSetInformationProcess
NtSetInformationResourceManager
NtSetInformationThread
NtSetInformationToken
NtSetInformationTransaction
NtSetQuotaInformationFile
NtSetSecurityObject
NtSetVolumeInformationFile
NtShutdownSystem
NtThawTransactions
NtTraceControl
NtTraceEvent
NtUnlockFile
NtVdmControl
NtWaitForSingleObject
NtWriteFile
ObAssignSecurity
ObCheckCreateObjectAccess
ObCheckObjectAccess
ObCloseHandle
ObCreateObject
ObCreateObjectType
ObDeleteCapturedInsertInfo
ObDereferenceObject
ObDereferenceObjectDeferDelete
ObDereferenceObjectDeferDeleteWithTag
ObDereferenceSecurityDescriptor
ObDuplicateObject
ObFindHandleForObject
ObGetFilterVersion
ObGetObjectSecurity
ObGetObjectType
ObInsertObject
ObIsDosDeviceLocallyMapped
ObIsKernelHandle
ObLogSecurityDescriptor
ObMakeTemporaryObject
ObOpenObjectByName
ObOpenObjectByPointer
ObOpenObjectByPointerWithTag
ObQueryNameInfo
ObQueryNameString
ObQueryObjectAuditingByHandle
ObReferenceObjectByHandle
ObReferenceObjectByHandleWithTag
ObReferenceObjectByName
ObReferenceObjectByPointer
ObReferenceObjectByPointerWithTag


ObReferenceSecurityDescriptor
ObRegisterCallbacks
ObReleaseObjectSecurity
ObSetHandleAttributes
ObSetSecurityDescriptorInfo
ObSetSecurityObjectByPointer
ObUnRegisterCallbacks
ObWaitForMultipleObjects
ObWaitForSingleObject




POGOBuffer
PcwAddInstance
PcwCloseInstance
PcwCreateInstance
PcwRegister
PcwUnregister
PfFileInfoNotify
PfxFindPrefix
PfxInitialize
PfxInsertPrefix
PfxRemovePrefix
PoAllProcessorsDeepIdle
PoCallDriver
PoCancelDeviceNotify
PoClearPowerRequest
PoCreatePowerRequest
PoDeletePowerRequest
PoDisableSleepStates
PoEndDeviceBusy
PoFxActivateComponent
PoFxCompleteDevicePowerNotRequired
PoFxCompleteIdleCondition
PoFxCompleteIdleState
PoFxIdleComponent
PoFxNotifySurprisePowerOn
PoFxPowerControl
PoFxProcessorNotification
PoFxRegisterCoreDevice
PoFxRegisterDevice
PoFxRegisterPlugin
PoFxRegisterPluginEx
PoFxRegisterPrimaryDevice
PoFxReportDevicePoweredOn
PoFxSetComponentLatency
PoFxSetComponentResidency
PoFxSetComponentWake
PoFxSetDeviceIdleTimeout
PoFxStartDevicePowerManagement
PoFxUnregisterDevice
PoFxUpdateSystemLatency
PoGetProcessorIdleAccounting
PoGetSystemWake
PoInitiateProcessorWake
PoLatencySensitivityHint
PoQueryWatchdogTime
PoQueueShutdownWorkItem
PoReenableSleepStates
PoRegisterDeviceForIdleDetection
PoRegisterDeviceNotify
PoRegisterPowerSettingCallback
PoRegisterSystemState
PoRequestPowerIrp
PoRequestShutdownEvent
PoSetDeviceBusyEx
PoSetFixedWakeSource
PoSetHiberRange
PoSetPowerRequest
PoSetPowerState
PoSetSystemState
PoSetSystemWake
PoShutdownBugCheck
PoStartDeviceBusy
PoStartNextPowerIrp
PoUnregisterPowerSettingCallback
PoUnregisterSystemState
PoUserShutdownCancelled
PoUserShutdownInitiated
ProbeForRead
ProbeForWrite
PsAcquireProcessExitSynchronization
PsAssignImpersonationToken
PsChargePoolQuota
PsChargeProcessNonPagedPoolQuota
PsChargeProcessPagedPoolQuota
PsChargeProcessPoolQuota
PsChargeProcessWakeCounter
PsCreateSystemThread
PsDereferenceImpersonationToken
PsDereferencePrimaryToken
PsDisableImpersonation
PsEnterPriorityRegion
PsEstablishWin32Callouts
PsGetContextThread
PsGetCurrentProcess
PsGetCurrentProcessId
PsGetCurrentProcessSessionId
PsGetCurrentProcessWin32Process
PsGetCurrentThread
PsGetCurrentThreadId
PsGetCurrentThreadPreviousMode
PsGetCurrentThreadProcess
PsGetCurrentThreadProcessId
PsGetCurrentThreadStackBase
PsGetCurrentThreadStackLimit
PsGetCurrentThreadTeb
PsGetCurrentThreadWin32Thread
PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion
PsGetJobLock
PsGetJobSessionId
PsGetJobUIRestrictionsClass
PsGetProcessCreateTimeQuadPart
PsGetProcessDebugPort
PsGetProcessExitProcessCalled
PsGetProcessExitStatus
PsGetProcessExitTime
PsGetProcessId
PsGetProcessImageFileName
PsGetProcessInheritedFromUniqueProcessId
PsGetProcessJob
PsGetProcessPeb
PsGetProcessPriorityClass
PsGetProcessSectionBaseAddress
PsGetProcessSecurityPort
PsGetProcessSessionId
PsGetProcessSessionIdEx
PsGetProcessWin32Process
PsGetProcessWin32WindowStation
PsGetThreadExitStatus
PsGetThreadFreezeCount
PsGetThreadHardErrorsAreDisabled
PsGetThreadId
PsGetThreadProcess
PsGetThreadProcessId
PsGetThreadSessionId
PsGetThreadTeb
PsGetThreadWin32Thread
PsGetVersion
PsImpersonateClient
PsInitialSystemProcess
PsIsCurrentThreadPrefetching
PsIsDiskCountersEnabled
PsIsProcessBeingDebugged
PsIsProtectedProcess
PsIsSystemProcess
PsIsSystemThread
PsIsThreadImpersonating
PsIsThreadTerminating
PsJobType
PsLeavePriorityRegion
PsLookupProcessByProcessId
PsLookupProcessThreadByCid
PsLookupThreadByThreadId
PsProcessType
PsQueryProcessExceptionFlags
PsReferenceImpersonationToken
PsReferencePrimaryToken
PsReferenceProcessFilePointer
PsReleaseProcessExitSynchronization
PsReleaseProcessWakeCounter
PsRemoveCreateThreadNotifyRoutine
PsRemoveLoadImageNotifyRoutine
PsRestoreImpersonation
PsResumeProcess
PsReturnPoolQuota
PsReturnProcessNonPagedPoolQuota
PsReturnProcessPagedPoolQuota
PsRevertThreadToSelf
PsRevertToSelf
PsSetContextThread
PsSetCreateProcessNotifyRoutine
PsSetCreateProcessNotifyRoutineEx
PsSetCreateThreadNotifyRoutine
PsSetCurrentThreadPrefetching
PsSetLegoNotifyRoutine
PsSetLoadImageNotifyRoutine
PsSetProcessPriorityByClass
PsSetProcessPriorityClass
PsSetProcessSecurityPort
PsSetProcessWin32Process
PsSetProcessWindowStation
PsSetThreadHardErrorsAreDisabled
PsSetThreadWin32Thread
PsSuspendProcess
PsTerminateSystemThread
PsThreadType
PsUILanguageComitted
PsUpdateDiskCounters
PsWrapApcWow64Thread
READ_REGISTER_BUFFER_UCHAR
READ_REGISTER_BUFFER_ULONG
READ_REGISTER_BUFFER_USHORT
READ_REGISTER_UCHAR
READ_REGISTER_ULONG
READ_REGISTER_USHORT
RtlAbsoluteToSelfRelativeSD
RtlAddAccessAllowedAce
RtlAddAccessAllowedAceEx
RtlAddAce
RtlAddAtomToAtomTable
RtlAddAtomToAtomTableEx
RtlAddRange
RtlAddResourceAttributeAce
RtlAllocateHeap
RtlAnsiCharToUnicodeChar
RtlAnsiStringToUnicodeSize
RtlAnsiStringToUnicodeString
RtlAppendAsciizToString
RtlAppendStringToString
RtlAppendUnicodeStringToString
RtlAppendUnicodeToString
RtlAreAllAccessesGranted
RtlAreAnyAccessesGranted
RtlAreBitsClear
RtlAreBitsSet
RtlAssert
RtlCaptureContext
RtlCaptureStackBackTrace
RtlCharToInteger
RtlCheckPortableOperatingSystem
RtlCheckRegistryKey
RtlCheckTokenCapability
RtlCheckTokenMembership
RtlCheckTokenMembershipEx
RtlClearAllBits
RtlClearBit
RtlClearBits
RtlCmDecodeMemIoResource
RtlCmEncodeMemIoResource
RtlCompareAltitudes
RtlCompareMemory
RtlCompareMemoryUlong
RtlCompareString
RtlCompareUnicodeString
RtlCompareUnicodeStrings
RtlCompressBuffer
RtlCompressChunks
RtlComputeCrc32
RtlContractHashTable
RtlConvertLongToLargeInteger
RtlConvertSidToUnicodeString
RtlConvertUlongToLargeInteger
RtlCopyBitMap
RtlCopyLuid
RtlCopyLuidAndAttributesArray
RtlCopyRangeList
RtlCopySid
RtlCopySidAndAttributesArray
RtlCopyString
RtlCopyUnicodeString
RtlCreateAcl
RtlCreateAtomTable
RtlCreateHashTable
RtlCreateHeap
RtlCreateRegistryKey
RtlCreateSecurityDescriptor
RtlCreateSystemVolumeInformationFolder
RtlCreateUnicodeString
RtlCreateUserThread
RtlCultureNameToLCID
RtlCustomCPToUnicodeN
RtlDecompressBuffer
RtlDecompressBufferEx
RtlDecompressChunks
RtlDecompressFragment
RtlDelete
RtlDeleteAce
RtlDeleteAtomFromAtomTable
RtlDeleteElementGenericTable
RtlDeleteElementGenericTableAvl
RtlDeleteElementGenericTableAvlEx
RtlDeleteHashTable
RtlDeleteNoSplay
RtlDeleteOwnersRanges
RtlDeleteRange
RtlDeleteRegistryValue
RtlDescribeChunk
RtlDestroyAtomTable
RtlDestroyHeap
RtlDowncaseUnicodeChar
RtlDowncaseUnicodeString
RtlDuplicateUnicodeString
RtlEmptyAtomTable
RtlEndEnumerationHashTable
RtlEndWeakEnumerationHashTable
RtlEnlargedIntegerMultiply
RtlEnlargedUnsignedDivide
RtlEnlargedUnsignedMultiply
RtlEnumerateEntryHashTable
RtlEnumerateGenericTable
RtlEnumerateGenericTableAvl
RtlEnumerateGenericTableLikeADirectory
RtlEnumerateGenericTableWithoutSplaying
RtlEnumerateGenericTableWithoutSplayingAvl
RtlEqualLuid
RtlEqualSid
RtlEqualString
RtlEqualUnicodeString
RtlEqualWnfChangeStamps
RtlEthernetAddressToStringA
RtlEthernetAddressToStringW
RtlEthernetStringToAddressA
RtlEthernetStringToAddressW
RtlExpandHashTable
RtlExtendedIntegerMultiply
RtlExtendedLargeIntegerDivide
RtlExtendedMagicDivide
RtlExtractBitMap
RtlFillMemory
RtlFillMemoryUlong
RtlFillMemoryUlonglong
RtlFindAceByType
RtlFindClearBits
RtlFindClearBitsAndSet
RtlFindClearRuns
RtlFindClosestEncodableLength
RtlFindFirstRunClear
RtlFindLastBackwardRunClear
RtlFindLeastSignificantBit
RtlFindLongestRunClear
RtlFindMessage
RtlFindMostSignificantBit
RtlFindNextForwardRunClear
RtlFindRange
RtlFindSetBits
RtlFindSetBitsAndClear
RtlFindUnicodePrefix
RtlFormatCurrentUserKeyPath
RtlFormatMessage
RtlFreeAnsiString
RtlFreeHeap
RtlFreeOemString
RtlFreeRangeList
RtlFreeUnicodeString
RtlGUIDFromString
RtlGenerate8dot3Name
RtlGenerateClass5Guid
RtlGetAce
RtlGetAppContainerNamedObjectPath
RtlGetCallersAddress
RtlGetCompressionWorkSpaceSize
RtlGetDaclSecurityDescriptor
RtlGetDefaultCodePage
RtlGetElementGenericTable
RtlGetElementGenericTableAvl
RtlGetEnabledExtendedFeatures
RtlGetFirstRange
RtlGetGroupSecurityDescriptor
RtlGetIntegerAtom
RtlGetLastRange
RtlGetNextEntryHashTable
RtlGetNextRange
RtlGetNtGlobalFlags
RtlGetOwnerSecurityDescriptor
RtlGetProductInfo
RtlGetSaclSecurityDescriptor
RtlGetSetBootStatusData
RtlGetThreadLangIdByIndex
RtlGetVersion
RtlHashUnicodeString
RtlIdnToAscii
RtlIdnToNameprepUnicode
RtlIdnToUnicode
RtlImageDirectoryEntryToData
RtlImageNtHeader
RtlInitAnsiString
RtlInitAnsiStringEx
RtlInitCodePageTable
RtlInitEnumerationHashTable
RtlInitString
RtlInitUnicodeString
RtlInitUnicodeStringEx
RtlInitWeakEnumerationHashTable
RtlInitializeBitMap
RtlInitializeGenericTable
RtlInitializeGenericTableAvl
RtlInitializeRangeList
RtlInitializeSid
RtlInitializeUnicodePrefix
RtlInsertElementGenericTable
RtlInsertElementGenericTableAvl
RtlInsertElementGenericTableFull
RtlInsertElementGenericTableFullAvl
RtlInsertEntryHashTable
RtlInsertUnicodePrefix
RtlInt64ToUnicodeString
RtlIntegerToChar
RtlIntegerToUnicode
RtlIntegerToUnicodeString
RtlInvertRangeList
RtlInvertRangeListEx
RtlIoDecodeMemIoResource
RtlIoEncodeMemIoResource
RtlIpv4AddressToStringA
RtlIpv4AddressToStringExA
RtlIpv4AddressToStringExW
RtlIpv4AddressToStringW
RtlIpv4StringToAddressA
RtlIpv4StringToAddressExA
RtlIpv4StringToAddressExW
RtlIpv4StringToAddressW
RtlIpv6AddressToStringA
RtlIpv6AddressToStringExA
RtlIpv6AddressToStringExW
RtlIpv6AddressToStringW
RtlIpv6StringToAddressA
RtlIpv6StringToAddressExA
RtlIpv6StringToAddressExW
RtlIpv6StringToAddressW
RtlIsGenericTableEmpty
RtlIsGenericTableEmptyAvl
RtlIsNameLegalDOS8Dot3
RtlIsNormalizedString
RtlIsNtDdiVersionAvailable
RtlIsRangeAvailable
RtlIsServicePackVersionInstalled
RtlIsValidOemCharacter
RtlLCIDToCultureName
RtlLargeIntegerAdd
RtlLargeIntegerArithmeticShift
RtlLargeIntegerDivide
RtlLargeIntegerNegate
RtlLargeIntegerShiftLeft
RtlLargeIntegerShiftRight
RtlLargeIntegerSubtract
RtlLengthRequiredSid
RtlLengthSecurityDescriptor
RtlLengthSid
RtlLoadString
RtlLocalTimeToSystemTime
RtlLockBootStatusData
RtlLookupAtomInAtomTable
RtlLookupElementGenericTable
RtlLookupElementGenericTableAvl
RtlLookupElementGenericTableFull
RtlLookupElementGenericTableFullAvl
RtlLookupEntryHashTable
RtlLookupFirstMatchingElementGenericTableAvl
RtlMapGenericMask
RtlMapSecurityErrorToNtStatus
RtlMergeRangeLists
RtlMoveMemory
RtlMultiByteToUnicodeN
RtlMultiByteToUnicodeSize
RtlNextUnicodePrefix
RtlNormalizeString
RtlNtStatusToDosError
RtlNtStatusToDosErrorNoTeb
RtlNumberGenericTableElements
RtlNumberGenericTableElementsAvl
RtlNumberOfClearBits
RtlNumberOfClearBitsInRange
RtlNumberOfSetBits
RtlNumberOfSetBitsInRange
RtlNumberOfSetBitsUlongPtr
RtlOemStringToCountedUnicodeString
RtlOemStringToUnicodeSize
RtlOemStringToUnicodeString
RtlOemToUnicodeN
RtlOpenCurrentUser
RtlOwnerAcesPresent
RtlPinAtomInAtomTable
RtlPrefixString
RtlPrefixUnicodeString
RtlQueryAtomInAtomTable
RtlQueryDynamicTimeZoneInformation
RtlQueryElevationFlags
RtlQueryInformationAcl
RtlQueryModuleInformation
RtlQueryRegistryValues
RtlQueryTimeZoneInformation
RtlQueryValidationRunlevel
RtlRaiseException
RtlRandom
RtlRandomEx
RtlRbInsertNodeEx
RtlRbRemoveNode
RtlRealPredecessor
RtlRealSuccessor
RtlRemoveEntryHashTable
RtlRemoveUnicodePrefix
RtlReplaceSidInSd
RtlReserveChunk
RtlRunOnceBeginInitialize
RtlRunOnceComplete
RtlRunOnceExecuteOnce
RtlRunOnceInitialize
RtlSecondsSince1970ToTime
RtlSecondsSince1980ToTime
RtlSelfRelativeToAbsoluteSD2
RtlSelfRelativeToAbsoluteSD
RtlSetAllBits
RtlSetBit
RtlSetBits
RtlSetControlSecurityDescriptor
RtlSetDaclSecurityDescriptor
RtlSetDynamicTimeZoneInformation
RtlSetGroupSecurityDescriptor
RtlSetOwnerSecurityDescriptor
RtlSetPortableOperatingSystem
RtlSetSaclSecurityDescriptor
RtlSetTimeZoneInformation
RtlSidHashInitialize
RtlSidHashLookup
RtlSizeHeap
RtlSplay
RtlStringFromGUID
RtlSubAuthorityCountSid
RtlSubAuthoritySid
RtlSubtreePredecessor
RtlSubtreeSuccessor
RtlSystemTimeToLocalTime
RtlTestBit
RtlTimeFieldsToTime
RtlTimeToElapsedTimeFields
RtlTimeToSecondsSince1970
RtlTimeToSecondsSince1980
RtlTimeToTimeFields
RtlTraceDatabaseAdd
RtlTraceDatabaseCreate
RtlTraceDatabaseDestroy
RtlTraceDatabaseEnumerate
RtlTraceDatabaseFind
RtlTraceDatabaseLock
RtlTraceDatabaseUnlock
RtlTraceDatabaseValidate
RtlUTF8ToUnicodeN
RtlUnicodeStringToAnsiSize
RtlUnicodeStringToAnsiString
RtlUnicodeStringToCountedOemString
RtlUnicodeStringToInteger
RtlUnicodeStringToOemSize
RtlUnicodeStringToOemString
RtlUnicodeToCustomCPN
RtlUnicodeToMultiByteN
RtlUnicodeToMultiByteSize
RtlUnicodeToOemN
RtlUnicodeToUTF8N
RtlUnlockBootStatusData
RtlUnwind
RtlUpcaseUnicodeChar
RtlUpcaseUnicodeString
RtlUpcaseUnicodeStringToAnsiString
RtlUpcaseUnicodeStringToCountedOemString
RtlUpcaseUnicodeStringToOemString
RtlUpcaseUnicodeToCustomCPN
RtlUpcaseUnicodeToMultiByteN
RtlUpcaseUnicodeToOemN
RtlUpperChar
RtlUpperString
RtlValidRelativeSecurityDescriptor
RtlValidSecurityDescriptor
RtlValidSid
RtlValidateUnicodeString
RtlVerifyVersionInfo
RtlVolumeDeviceToDosName
RtlWalkFrameChain
RtlWeaklyEnumerateEntryHashTable
RtlWriteRegistryValue
RtlZeroHeap
RtlZeroMemory
RtlxAnsiStringToUnicodeSize
RtlxOemStringToUnicodeSize
RtlxUnicodeStringToAnsiSize
RtlxUnicodeStringToOemSize
SeAccessCheck
SeAccessCheckEx
SeAccessCheckFromState
SeAccessCheckFromStateEx
SeAccessCheckWithHint
SeAppendPrivileges
SeAssignSecurity
SeAssignSecurityEx
SeAuditHardLinkCreation
SeAuditHardLinkCreationWithTransaction
SeAuditTransactionStateChange
SeAuditingAnyFileEventsWithContext
SeAuditingFileEvents
SeAuditingFileEventsWithContext
SeAuditingFileOrGlobalEvents
SeAuditingHardLinkEvents
SeAuditingHardLinkEventsWithContext
SeCaptureSecurityDescriptor
SeCaptureSubjectContext
SeCaptureSubjectContextEx
SeCloseObjectAuditAlarm
SeCloseObjectAuditAlarmForNonObObject
SeComputeAutoInheritByObjectType
SeCreateAccessState
SeCreateAccessStateEx
SeCreateClientSecurity
SeCreateClientSecurityEx
SeCreateClientSecurityFromSubjectContext
SeCreateClientSecurityFromSubjectContextEx
SeDeassignSecurity
SeDeleteAccessState
SeDeleteObjectAuditAlarm
SeDeleteObjectAuditAlarmWithTransaction
SeExamineSacl
SeExports
SeFilterToken
SeFreePrivileges
SeGetLinkedToken
SeGetLogonSessionToken
SeImpersonateClient
SeImpersonateClientEx
SeLocateProcessImageName
SeLockSubjectContext
SeMarkLogonSessionForTerminationNotification
SeOpenObjectAuditAlarm
SeOpenObjectAuditAlarmForNonObObject
SeOpenObjectAuditAlarmWithTransaction
SeOpenObjectForDeleteAuditAlarm
SeOpenObjectForDeleteAuditAlarmWithTransaction
SePrivilegeCheck
SePrivilegeObjectAuditAlarm
SePublicDefaultDacl
SeQueryAuthenticationIdToken
SeQueryInformationToken
SeQuerySecurityAttributesToken
SeQuerySecurityDescriptorInfo
SeQuerySessionIdToken
SeRegisterLogonSessionTerminatedRoutine
SeReleaseSecurityDescriptor
SeReleaseSubjectContext
SeReportSecurityEvent
SeReportSecurityEventWithSubCategory
SeSecurityAttributePresent
SeSetAccessStateGenericMapping
SeSetAuditParameter
SeSetSecurityAttributesToken
SeSetSecurityDescriptorInfo
SeSetSecurityDescriptorInfoEx
SeSinglePrivilegeCheck
SeSrpAccessCheck
SeSystemDefaultDacl
SeTokenFromAccessInformation
SeTokenImpersonationLevel
SeTokenIsAdmin
SeTokenIsRestricted
SeTokenIsWriteRestricted
SeTokenObjectType
SeTokenType
SeUnlockSubjectContext
SeUnregisterLogonSessionTerminatedRoutine
SeValidSecurityDescriptor
TmCancelPropagationRequest
TmCommitComplete
TmCommitEnlistment
TmCommitTransaction
TmCreateEnlistment
TmCurrentTransaction
TmDereferenceEnlistmentKey
TmEnableCallbacks
TmEndPropagationRequest
TmEnlistmentObjectType
TmFreezeTransactions
TmGetTransactionId
TmInitSystem
TmInitSystemPhase2
TmInitializeResourceManager
TmInitializeTransaction
TmInitializeTransactionManager
TmIsKTMCommitCoordinator
TmIsTransactionActive
TmPrePrepareComplete
TmPrePrepareEnlistment
TmPrepareComplete
TmPrepareEnlistment
TmPropagationComplete
TmPropagationFailed
TmReadOnlyEnlistment
TmRecoverEnlistment
TmRecoverResourceManager
TmRecoverTransactionManager
TmReferenceEnlistmentKey
TmRenameTransactionManager
TmRequestOutcomeEnlistment
TmResourceManagerObjectType
TmRollbackComplete
TmRollbackEnlistment
TmRollbackTransaction
TmSetCurrentTransaction
TmSinglePhaseReject
TmThawTransactions
TmTransactionManagerObjectType
TmTransactionObjectType
VerSetConditionMask
VfFailDeviceNode
VfFailDriver
VfFailSystemBIOS
VfIsVerificationEnabled
WRITE_REGISTER_BUFFER_UCHAR
WRITE_REGISTER_BUFFER_ULONG
WRITE_REGISTER_BUFFER_USHORT
WRITE_REGISTER_UCHAR
WRITE_REGISTER_ULONG
WRITE_REGISTER_USHORT
WheaAddErrorSource
WheaConfigureErrorSource
WheaGetErrorSource
WheaInitializeRecordHeader
WheaReportHwError
WmiQueryTraceInformation
WmiTraceMessage
WmiTraceMessageVa
XIPDispatch
ZwAccessCheckAndAuditAlarm
ZwAddBootEntry
ZwAddDriverEntry
ZwAdjustPrivilegesToken
ZwAlertThread
ZwAllocateLocallyUniqueId
ZwAllocateVirtualMemory
ZwAlpcAcceptConnectPort
ZwAlpcCancelMessage
ZwAlpcConnectPort
ZwAlpcConnectPortEx
ZwAlpcCreatePort
ZwAlpcCreatePortSection
ZwAlpcCreateResourceReserve
ZwAlpcCreateSectionView
ZwAlpcCreateSecurityContext
ZwAlpcDeletePortSection
ZwAlpcDeleteResourceReserve
ZwAlpcDeleteSectionView
ZwAlpcDeleteSecurityContext
ZwAlpcDisconnectPort
ZwAlpcQueryInformation
ZwAlpcSendWaitReceivePort
ZwAlpcSetInformation
ZwAssignProcessToJobObject
ZwCancelIoFile
ZwCancelTimer
ZwClearEvent
ZwClose
ZwCloseObjectAuditAlarm
ZwCommitComplete
ZwCommitEnlistment
ZwCommitTransaction
ZwConnectPort
ZwCreateDirectoryObject
ZwCreateEnlistment
ZwCreateEvent
ZwCreateFile
ZwCreateIoCompletion
ZwCreateJobObject
ZwCreateKey
ZwCreateKeyTransacted
ZwCreateResourceManager
ZwCreateSection
ZwCreateSymbolicLinkObject
ZwCreateTimer
ZwCreateTransaction
ZwCreateTransactionManager
ZwCreateWnfStateName
ZwDeleteBootEntry
ZwDeleteDriverEntry
ZwDeleteFile
ZwDeleteKey
ZwDeleteValueKey
ZwDeleteWnfStateData
ZwDeleteWnfStateName
ZwDeviceIoControlFile
ZwDisplayString
ZwDuplicateObject
ZwDuplicateToken
ZwEnumerateBootEntries
ZwEnumerateDriverEntries
ZwEnumerateKey
ZwEnumerateTransactionObject
ZwEnumerateValueKey
ZwFlushBuffersFile
ZwFlushBuffersFileEx
ZwFlushInstructionCache
ZwFlushKey
ZwFlushVirtualMemory
ZwFreeVirtualMemory
ZwFsControlFile
ZwGetNotificationResourceManager
ZwImpersonateAnonymousToken
ZwInitiatePowerAction
ZwIsProcessInJob
ZwLoadDriver
ZwLoadKey
ZwLoadKeyEx
ZwLockFile
ZwLockProductActivationKeys
ZwMakeTemporaryObject
ZwMapViewOfSection
ZwModifyBootEntry
ZwModifyDriverEntry
ZwNotifyChangeKey
ZwNotifyChangeSession
ZwOpenDirectoryObject
ZwOpenEnlistment
ZwOpenEvent
ZwOpenFile
ZwOpenJobObject
ZwOpenKey
ZwOpenKeyEx
ZwOpenKeyTransacted
ZwOpenKeyTransactedEx
ZwOpenProcess
ZwOpenProcessToken
ZwOpenProcessTokenEx
ZwOpenResourceManager
ZwOpenSection
ZwOpenSession
ZwOpenSymbolicLinkObject
ZwOpenThread
ZwOpenThreadToken
ZwOpenThreadTokenEx
ZwOpenTimer
ZwOpenTransaction
ZwOpenTransactionManager
ZwPowerInformation
ZwPrePrepareComplete
ZwPrePrepareEnlistment
ZwPrepareComplete
ZwPrepareEnlistment
ZwPropagationComplete
ZwPropagationFailed
ZwPulseEvent
ZwQueryBootEntryOrder
ZwQueryBootOptions
ZwQueryDefaultLocale
ZwQueryDefaultUILanguage
ZwQueryDirectoryFile
ZwQueryDirectoryObject
ZwQueryDriverEntryOrder
ZwQueryEaFile
ZwQueryFullAttributesFile
ZwQueryInformationEnlistment
ZwQueryInformationFile
ZwQueryInformationJobObject
ZwQueryInformationProcess
ZwQueryInformationResourceManager
ZwQueryInformationThread
ZwQueryInformationToken
ZwQueryInformationTransaction
ZwQueryInformationTransactionManager
ZwQueryInstallUILanguage
ZwQueryKey
ZwQueryLicenseValue
ZwQueryObject
ZwQueryQuotaInformationFile
ZwQuerySection
ZwQuerySecurityAttributesToken
ZwQuerySecurityObject
ZwQuerySymbolicLinkObject
ZwQuerySystemInformation
ZwQueryValueKey
ZwQueryVirtualMemory
ZwQueryVolumeInformationFile
ZwQueryWnfStateData
ZwQueryWnfStateNameInformation
ZwReadFile
ZwReadOnlyEnlistment
ZwRecoverEnlistment
ZwRecoverResourceManager
ZwRecoverTransactionManager
ZwRemoveIoCompletion
ZwRemoveIoCompletionEx
ZwRenameKey
ZwReplaceKey
ZwRequestPort
ZwRequestWaitReplyPort
ZwResetEvent
ZwRestoreKey
ZwRollbackComplete
ZwRollbackEnlistment
ZwRollbackTransaction
ZwSaveKey
ZwSaveKeyEx
ZwSecureConnectPort
ZwSetBootEntryOrder
ZwSetBootOptions
ZwSetDefaultLocale
ZwSetDefaultUILanguage
ZwSetDriverEntryOrder
ZwSetEaFile
ZwSetEvent
ZwSetInformationEnlistment
ZwSetInformationFile
ZwSetInformationJobObject
ZwSetInformationKey
ZwSetInformationObject
ZwSetInformationProcess
ZwSetInformationResourceManager
ZwSetInformationThread
ZwSetInformationToken
ZwSetInformationTransaction
ZwSetQuotaInformationFile
ZwSetSecurityObject
ZwSetSystemInformation
ZwSetSystemTime
ZwSetTimer
ZwSetTimerEx
ZwSetValueKey
ZwSetVolumeInformationFile
ZwTerminateJobObject
ZwTerminateProcess
ZwTraceEvent
ZwTranslateFilePath
ZwUnloadDriver
ZwUnloadKey
ZwUnloadKeyEx
ZwUnlockFile
ZwUnlockVirtualMemory
ZwUnmapViewOfSection
ZwUpdateWnfStateData
ZwWaitForMultipleObjects
ZwWaitForSingleObject
ZwWriteFile
ZwYieldExecution
_CIcos
_CIsin
_CIsqrt
_abnormal_termination
_alldiv
_alldvrm
_allmul
_alloca_probe
_alloca_probe_16
_alloca_probe_8
_allrem
_allshl
_allshr
_aulldiv
_aulldvrm
_aullrem
_aullshr
_chkstk
_except_handler2
_except_handler3
_global_unwind2
_i64toa_s
_i64tow_s
_itoa
_itoa_s
_itow
_itow_s
_local_unwind2
_ltoa_s
_ltow_s
_makepath_s
_purecall
_snprintf
_snprintf_s
_snscanf_s
_snwprintf
_snwprintf_s
_snwscanf_s
_splitpath_s
_stricmp
_strlwr
_strnicmp
_strnset
_strnset_s
_strrev
_strset
_strset_s
_strtoui64
_strupr
_swprintf
_ui64toa_s
_ui64tow_s
_ultoa_s
_ultow_s
_vsnprintf
_vsnprintf_s
_vsnwprintf
_vsnwprintf_s
_vswprintf
_wcsicmp
_wcslwr
_wcsnicmp
_wcsnset
_wcsnset_s
_wcsrev
_wcsset_s
_wcsupr
_wmakepath_s
_wsplitpath_s
_wtoi
_wtol
atoi
atol
bsearch
bsearch_s
isdigit
islower
isprint
isspace
isupper
isxdigit
mbstowcs
mbtowc
memchr
memcmp
memcpy
memcpy_s
memmove
memmove_s
memset
psMUITest
qsort
rand
sprintf
sprintf_s
srand
sscanf_s
strcat
strcat_s
strchr
strcmp
strcpy
strcpy_s
strlen
strncat
strncat_s
strncmp
strncpy
strncpy_s
strnlen
strrchr
strspn
strstr
strtok_s
swprintf
swprintf_s
swscanf_s
tolower
toupper
towlower
towupper
vDbgPrintEx
vDbgPrintExWithPrefix
vsprintf
vsprintf_s
vswprintf_s
wcscat
wcscat_s
wcschr
wcscmp
wcscpy
wcscpy_s
wcscspn
wcslen
wcsncat
wcsncat_s
wcsncmp
wcsncpy
wcsncpy_s
wcsnlen
wcsrchr
wcsspn
wcsstr
wcstombs
wcstoul
wctomb
