
#include <ntoskrnl.h>
#include <gentrace.h>

#undef ExEnterCriticalRegionAndAcquireFastMutexUnsafe
#undef ExReleaseFastMutexUnsafeAndLeaveCriticalRegion
#undef InterlockedIncrement
#undef InterlockedDecrement
#undef InterlockedExchange
#undef InterlockedCompareExchange
#undef KeGetCurrentThread
#undef KeAcquireGuardedMutex
#undef KeInitializeGuardedMutex
#undef KeReleaseGuardedMutex

LONG __fastcall InterlockedIncrement(LONG volatile *Destination);
LONG __fastcall InterlockedDecrement(LONG volatile *Destination);
LONG __fastcall InterlockedExchange(LONG volatile *Destination, LONG Exchange);
LONG __fastcall InterlockedCompareExchange(LONG volatile *Destination, LONG Exchange, LONG Comparand);
PVOID NTAPI PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion(HANDLE* OutProcessId);
VOID NTAPI ObDeleteCapturedInsertInfo(IN PVOID Object);
VOID NTAPI _KeLeaveCriticalRegion(VOID);
BOOLEAN NTAPI KeRemoveSystemServiceTable(ULONG Index);
PEPROCESS NTAPI PsGetThreadProcess(PETHREAD Thread);
PEJOB NTAPI PsGetProcessJob(PEPROCESS Process);
PPEB NTAPI PsGetProcessPeb(PEPROCESS Process);
KPROCESSOR_MODE NTAPI PsGetCurrentThreadPreviousMode(VOID);
LPSTR NTAPI PsGetProcessImageFileName(PEPROCESS Process);
PVOID NTAPI PsGetCurrentThreadStackBase(VOID);

typedef ULONG TAG;
typedef int INT;
typedef unsigned int UINT;


_NOTRACE_(DbgBreakPoint)
_NOTRACE_(DbgPrint)
_NOTRACE_(DbgPrompt)
_TRACEF_(BOOLEAN, ExfAcquireRundownProtection, 1, PVOID)
_TRACE_(PVOID, ExAllocatePoolWithQuotaTag, 3, ULONG, SIZE_T, ULONG)
_TRACE_(PVOID, ExAllocatePoolWithTag, 3, ULONG, ULONG, TAG)
_EXPORT(ExAllocatePoolWithTagPriority)
_VTRACE_(VOID, ExDeletePagedLookasideList, 1, PVOID)
_TRACE_(NTSTATUS, ExDeleteResourceLite, 1, PVOID)
_VTRACEF_(VOID, ExEnterCriticalRegionAndAcquireFastMutexUnsafe, 1, PVOID)
_TRACE_(PVOID, ExEnterCriticalRegionAndAcquireResourceExclusive, 1, PVOID)
_EXPORT(ExEnterCriticalRegionAndAcquireResourceShared)
_EXPORT(ExFreePool)
_VTRACE_(VOID, ExFreePoolWithTag, 2, PVOID, ULONG)
_EXPORT(ExGetExclusiveWaiterCount)
_EXPORT(ExGetSharedWaiterCount)
_VTRACE_(VOID, ExInitializePagedLookasideList, 7, PVOID, PVOID, PVOID, ULONG, SIZE_T, ULONG, USHORT)
_TRACE_(NTSTATUS, ExInitializeResourceLite, 1, PVOID)
_VTRACEF_(VOID, ExfInitializeRundownProtection, 1, PVOID)
_TRACE_(BOOLEAN, ExIsProcessorFeaturePresent, 1, ULONG)
_TRACE_(BOOLEAN, ExIsResourceAcquiredExclusiveLite, 1, PVOID)
_EXPORT(ExIsResourceAcquiredSharedLite)
_EXPORT(ExQueryPoolBlockSize)
_EXPORT(ExRaiseAccessViolation)
_EXPORT(ExRaiseDatatypeMisalignment)
_EXPORT(ExRaiseHardError)
_EXPORT2(ExRaiseStatus, RtlRaiseStatus)
_VTRACEF_(VOID, ExReleaseFastMutexUnsafeAndLeaveCriticalRegion, 1, PVOID)
_VTRACEF_(VOID, ExReleaseResourceAndLeaveCriticalRegion, 1, PVOID)
_VTRACEF_(VOID, ExfReleaseRundownProtection, 1, PVOID)
_VTRACEF_(VOID, ExfRundownCompleted, 1, PVOID)
_EXPORT(ExSystemTimeToLocalTime)
_VTRACEF_(VOID, ExfWaitForRundownProtectionRelease, 1, PVOID)
_EXPORT(InitSafeBootMode)
_TRACEF_(LONG, InterlockedCompareExchange, 3, PVOID, LONG, LONG)
_TRACEF_(LONG, InterlockedDecrement, 1, PVOID)
_TRACEF_(LONG, InterlockedExchange, 2, PVOID, LONG)
_TRACEF_(LONG, InterlockedIncrement, 1, PVOID)
_TRACEF_(PVOID, InterlockedPopEntrySList, 1, PVOID)
_TRACEF_(PVOID, InterlockedPushEntrySList, 2, PVOID, PVOID)
_EXPORT(IoAllocateErrorLogEntry)
_EXPORT(IoBuildAsynchronousFsdRequest)
//_TRACE_(PVOID, IoBuildDeviceIoControlRequest, 9, ULONG, PVOID, PVOID, ULONG, PVOID, ULONG, BOOLEAN, PVOID, PVOID)
_NOTRACE_(IoBuildDeviceIoControlRequest)
_TRACE_(PVOID, IoBuildSynchronousFsdRequest, 7, ULONG, PVOID, PVOID, ULONG, PVOID, PVOID, PVOID)
_EXPORT(IoCreateDriver)
//_TRACE_(NTSTATUS, IoCreateFile, 3, PVOID, PVOID, PVOID)
_NOTRACE_(IoCreateFile)
_EXPORT(IoDriverObjectType)
_EXPORT2(IoFileObjectType, _IoFileObjectType)
_EXPORT(IoGetDeviceInterfaces)
_TRACE_(NTSTATUS, IoGetDeviceObjectPointer, 4, PUNICODE_STRING, ULONG, PVOID, PVOID)
_EXPORT(IoGetDeviceProperty)
_EXPORT(IoGetRelatedDeviceObject)
_EXPORT(IoGetStackLimits)
_EXPORT(IoInvalidateDeviceRelations)
_EXPORT(IoOpenDeviceInterfaceRegistryKey)
_EXPORT(IoOpenDeviceRegistryKey)
_EXPORT(IoPnPDeliverServicePowerNotification)
_EXPORT(IoQueryDeviceDescription)
_EXPORT(IoQueueThreadIrp)
_EXPORT(IoRegisterPlugPlayNotification)
_TRACE_(BOOLEAN, IoSetThreadHardErrorMode, 1, BOOLEAN)
_EXPORT(IoSynchronousInvalidateDeviceRelations)
_EXPORT(IoUnregisterPlugPlayNotification)
_EXPORT(IoWMIHandleToInstanceName)
_EXPORT(IoWMIOpenBlock)
_EXPORT(IoWMIQuerySingleInstance)
_EXPORT(IoWriteErrorLogEntry)
_TRACEF_(NTSTATUS, IofCallDriver, 2, PVOID, PVOID)
_VTRACEF_(VOID, KeAcquireGuardedMutex, 1, PVOID)
_TRACE_(NTSTATUS, KeAddSystemServiceTable, 5, PVOID, PVOID, UINT, PVOID, UINT)
_EXPORT(KeAreAllApcsDisabled)
_EXPORT(KeAreApcsDisabled)
_VTRACE_(VOID, KeAttachProcess, 1, PVOID)
_VTRACE_(VOID, KeBugCheckEx, 5, ULONG, ULONG, ULONG, ULONG, ULONG)
_EXPORT(KeCancelTimer)
_EXPORT(KeClearEvent)
_EXPORT(KeDelayExecutionThread)
_VTRACE_(VOID, KeDetachProcess, 0)
_EXPORT2(KeEnterCriticalRegion, _KeEnterCriticalRegion)
_TRACE_(PVOID, KeGetCurrentThread, 0)
_VTRACE_(VOID, KeInitializeDpc, 3, PVOID, PVOID, PVOID)
_VTRACE_(VOID, KeInitializeEvent, 3, PVOID, ULONG, ULONG)
_VTRACEF_(VOID, KeInitializeGuardedMutex, 1, PVOID)
_EXPORT(KeInitializeTimer)
_EXPORT(KeInitializeTimerEx)
_EXPORT(KeIsAttachedProcess)
_VTRACE_(VOID, _KeLeaveCriticalRegion, 0)
_EXPORT(KePulseEvent)
_NOTRACE_(KeQueryInterruptTime)
_VTRACE_(VOID, KeQuerySystemTime, 1, PVOID)
_EXPORT(KeReadStateEvent)
_VTRACEF_(VOID, KeReleaseGuardedMutex, 1, PVOID)
_TRACE_(BOOLEAN, KeRemoveSystemServiceTable, 1, ULONG)
_EXPORT(KeResetEvent)
_TRACE_(NTSTATUS, KeRestoreFloatingPointState, 1, PVOID)
_TRACE_(NTSTATUS, KeSaveFloatingPointState, 1, PVOID)
_EXPORT(KeSetEvent)
_EXPORT(KeSetKernelStackSwapEnable)
_EXPORT(KeSetPriorityThread)
_EXPORT(KeSetTimer)
_EXPORT(KeStackAttachProcess)
_EXPORT(KeTickCount)
_EXPORT(KeUnstackDetachProcess)
_EXPORT(KeUserModeCallback)
_EXPORT(KeWaitForMultipleObjects)
_EXPORT(KeWaitForSingleObject)
_TRACE_(NTSTATUS, LdrAccessResource, 4, PVOID, PVOID, PVOID, PVOID)
_TRACE_(NTSTATUS, LdrFindResourceDirectory_U, 4, PVOID, PVOID, ULONG, PVOID)
_TRACE_(NTSTATUS, LdrFindResource_U, 4, PVOID, PVOID, ULONG, PVOID)
_EXPORT(LpcRequestPort)
_EXPORT(LpcRequestWaitReplyPort)
_TRACE_(NTSTATUS, MmAddVerifierThunks, 2, PVOID, ULONG)
_EXPORT(MmAdjustWorkingSetSize)
_EXPORT(MmCommitSessionMappedView)
_TRACE_(NTSTATUS, MmCreateSection, 8, PVOID, ULONG, PVOID, PVOID, ULONG, ULONG, PVOID, PVOID)
_TRACE_(PVOID, MmGetSystemRoutineAddress, 1, PUNICODE_STRING)
_EXPORT(MmGrowKernelStack)
_EXPORT(MmHighestUserAddress)
_TRACE_(NTSTATUS, MmIsVerifierEnabled, 1, PVOID)
_TRACE_(NTSTATUS, MmMapViewInSessionSpace, 3, PVOID, PVOID, PVOID)
//_TRACE_(NTSTATUS, MmMapViewOfSection, 1, PVOID)
_NOTRACE_(MmMapViewOfSection)
_TRACE_(PVOID, MmPageEntireDriver, 1, PVOID)
_TRACE_(ULONG, MmQuerySystemSize, 0)
_TRACE_(HANDLE, MmSecureVirtualMemory, 3, PVOID, ULONG, ULONG)
_TRACE_(NTSTATUS, MmUnmapViewInSessionSpace, 1, PVOID)
_TRACE_(NTSTATUS, MmUnmapViewOfSection, 2, PVOID, PVOID)
_EXPORT(MmUnsecureVirtualMemory)
_EXPORT(NlsAnsiCodePage)
_EXPORT(NlsMbCodePageTag)
_EXPORT(NlsOemCodePage)
_TRACE_(NTSTATUS, NtQueryInformationProcess, 5, HANDLE, ULONG, PVOID, ULONG, PVOID)
_EXPORT(ObAssignSecurity)
_EXPORT(ObCheckCreateObjectAccess)
_EXPORT(ObCheckObjectAccess)
_EXPORT(ObCloseHandle)
_EXPORT(ObCreateObject)
_VTRACE_(VOID, ObDeleteCapturedInsertInfo, 1, PVOID)
_EXPORT(ObFindHandleForObject)
_EXPORT(ObGetObjectSecurity)
_EXPORT(ObInsertObject)
_EXPORT(ObOpenObjectByName)
_TRACE_(NTSTATUS, ObOpenObjectByPointer, 7, PVOID, ULONG, PVOID, ULONG, PVOID, UCHAR, PVOID)
_EXPORT(ObQueryNameString)
_TRACE_(NTSTATUS, ObReferenceObjectByHandle, 6, HANDLE, ULONG, PVOID, UCHAR, PVOID, PVOID)
_EXPORT(ObReferenceObjectByName)
_EXPORT(ObReferenceObjectByPointer)
_EXPORT(ObReleaseObjectSecurity)
_EXPORT(ObSetHandleAttributes)
_EXPORT(ObSetSecurityDescriptorInfo)
_TRACEF_(LONG, ObfDereferenceObject, 1, PVOID)
_TRACEF_(LONG, ObfReferenceObject, 1, PVOID)
_EXPORT(PoRequestShutdownEvent)
_EXPORT(PoSetSystemState)
_EXPORT(ProbeForWrite)
_EXPORT(PsCreateSystemThread)
_EXPORT(PsDereferencePrimaryToken)
_VTRACE_(VOID, PsEstablishWin32Callouts, 1, PVOID)
_TRACE_(PVOID, IoGetCurrentProcess, 0)
_TRACE_(HANDLE, PsGetCurrentProcessId, 0)
_TRACE_(ULONG, PsGetCurrentProcessSessionId, 0)
_TRACE_(PVOID, PsGetCurrentProcessWin32Process, 0)
_TRACE_(HANDLE, PsGetCurrentThreadId, 0)
_TRACE_(UCHAR, PsGetCurrentThreadPreviousMode, 0)
_EXPORT(PsGetCurrentThreadProcessId)
_TRACE_(PVOID, PsGetCurrentThreadStackBase, 0)
_EXPORT(PsGetCurrentThreadTeb)
_TRACE_(PVOID, PsGetCurrentThreadWin32Thread, 0)
_TRACE_(PVOID, PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion, 1, PVOID)
_EXPORT(PsGetJobLock)
_EXPORT(PsGetJobSessionId)
_EXPORT(PsGetJobUIRestrictionsClass)
_EXPORT(PsGetProcessCreateTimeQuadPart)
_EXPORT(PsGetProcessDebugPort)
_EXPORT(PsGetProcessExitProcessCalled)
_EXPORT(PsGetProcessExitStatus)
_TRACE_(HANDLE, PsGetProcessId, 1, PVOID)
_TRACE_(PVOID, PsGetProcessImageFileName, 1, PVOID)
_TRACE_(HANDLE, PsGetProcessInheritedFromUniqueProcessId, 1, PVOID)
_TRACE_(PVOID, PsGetProcessJob, 1, PVOID)
_TRACE_(PVOID, PsGetProcessPeb, 1, PVOID)
_EXPORT(PsGetProcessPriorityClass)
_EXPORT(PsGetProcessSectionBaseAddress)
_TRACE_(HANDLE, PsGetProcessSessionId, 1, PVOID)
_EXPORT(PsGetProcessSessionIdEx)
_TRACE_(PVOID, PsGetProcessWin32Process, 1, PVOID)
_EXPORT(PsGetProcessWin32WindowStation)
_EXPORT(PsGetThreadFreezeCount)
_TRACE_(HANDLE, PsGetThreadId, 1, PVOID)
_TRACE_(PVOID, PsGetThreadProcess, 1, PVOID)
_TRACE_(HANDLE, PsGetThreadProcessId, 1, PVOID)
_EXPORT(PsGetThreadSessionId)
_EXPORT(PsGetThreadTeb)
_TRACE_(PVOID, PsGetThreadWin32Thread, 1, PVOID)
_EXPORT(PsIsSystemProcess)
_EXPORT(PsIsSystemThread)
_EXPORT(PsIsThreadTerminating)
_TRACE_(NTSTATUS, PsLookupProcessByProcessId, 2, HANDLE, PVOID)
_EXPORT(PsLookupThreadByThreadId)
_TRACE_(PVOID, PsReferenceImpersonationToken, 4, PVOID, PVOID, PVOID, PVOID)
_TRACE_(PVOID, PsReferencePrimaryToken, 1, PVOID)
_EXPORT(PsRevertToSelf)
_EXPORT(PsSetProcessPriorityByClass)
_EXPORT(PsSetProcessPriorityClass)
_TRACE_(NTSTATUS, PsSetProcessWin32Process, 3, PVOID, PVOID, PVOID)
_EXPORT(PsSetProcessWindowStation)
_TRACE_(PVOID, PsSetThreadWin32Thread, 3, PVOID, PVOID, PVOID)
_EXPORT(PsTerminateSystemThread)
_TRACE_(NTSTATUS, RtlAddAce, 5, PVOID, ULONG, ULONG, PVOID, ULONG)
_TRACE_(NTSTATUS, RtlAddAtomToAtomTable, 3, PVOID, PWSTR, PVOID)
_TRACE_(PVOID, RtlAllocateHeap, 3, PVOID, ULONG, SIZE_T)
_EXPORT(RtlAnsiStringToUnicodeString)
_EXPORT(RtlAppendUnicodeStringToString)
_TRACE_(NTSTATUS, RtlAppendUnicodeToString, 2, PUNICODE_STRING, PWSTR)
_EXPORT(RtlAreAllAccessesGranted)
_EXPORT(RtlAreAnyAccessesGranted)
_VTRACE_(VOID, RtlAssert, 4, PVOID, PVOID, ULONG, PVOID)
_NOTRACE_(RtlCaptureStackBackTrace)
_EXPORT(RtlCharToInteger)
_TRACE_(NTSTATUS, RtlCheckRegistryKey, 2, ULONG, PWSTR)
_EXPORT(RtlClearBits)
_VTRACE_(VOID, RtlCompareMemory, 3, PVOID, PVOID, ULONG)
_EXPORT(RtlCompareUnicodeString)
_TRACE_(NTSTATUS, RtlCopySid, 3, ULONG, PVOID, PVOID)
_VTRACE_(VOID, RtlCopyUnicodeString, 2, PUNICODE_STRING, PVOID)
_TRACE_(NTSTATUS, RtlCreateAcl, 3, PVOID, ULONG, ULONG)
_TRACE_(NTSTATUS, RtlCreateAtomTable, 2, ULONG, PVOID)
_TRACE_(HANDLE, RtlCreateHeap, 6, ULONG, PVOID, SIZE_T, SIZE_T, PVOID, PVOID)
_EXPORT(RtlCreateRegistryKey)
_TRACE_(NTSTATUS, RtlCreateSecurityDescriptor, 2, PVOID, ULONG)
_EXPORT(RtlCustomCPToUnicodeN)
_EXPORT(RtlDeleteAtomFromAtomTable)
_EXPORT(RtlDeleteElementGenericTableAvl)
_EXPORT(RtlDestroyAtomTable)
_EXPORT(RtlDestroyHeap)
_EXPORT(RtlEmptyAtomTable)
_EXPORT(RtlEnumerateGenericTableAvl)
_EXPORT(RtlEqualSid)
_EXPORT(RtlEqualUnicodeString)
_EXPORT(RtlExtendedLargeIntegerDivide)
_EXPORT(RtlFillMemoryUlong)
_TRACE_(NTSTATUS, RtlFindMessage, 5, PVOID, ULONG, ULONG, ULONG, PVOID)
_EXPORT(RtlFormatCurrentUserKeyPath)
_EXPORT(RtlFreeAnsiString)
_EXPORT(RtlFreeHeap)
_EXPORT(RtlFreeUnicodeString)
_NOTRACE_(RtlGetCallersAddress)
_VTRACE_(VOID, RtlGetDefaultCodePage, 2, PVOID, PVOID)
_TRACE_(ULONG, RtlGetNtGlobalFlags, 0)
_EXPORT(RtlImageDirectoryEntryToData)
_EXPORT(RtlImageNtHeader)
_EXPORT(RtlInitAnsiString)
_EXPORT(RtlInitCodePageTable)
_VTRACE_(VOID, RtlInitUnicodeString, 2, PVOID, PWSTR)
_EXPORT(RtlInitializeBitMap)
_VTRACE_(VOID, RtlInitializeGenericTableAvl, 5, PVOID, PVOID, PVOID, PVOID, PVOID)
_EXPORT(RtlInitializeSid)
_EXPORT(RtlInsertElementGenericTableAvl)
_EXPORT(RtlIntegerToChar)
_EXPORT(RtlIntegerToUnicode)
_TRACE_(NTSTATUS, RtlIntegerToUnicodeString, 3, ULONG, ULONG, PUNICODE_STRING)
_EXPORT(RtlLengthRequiredSid)
_TRACE_(ULONG, RtlLengthSid, 1, PVOID)
_EXPORT(RtlLookupAtomInAtomTable)
_EXPORT(RtlLookupElementGenericTableAvl)
_EXPORT(RtlMapGenericMask)
_TRACE_(NTSTATUS, RtlMultiByteToUnicodeN, 5, PWSTR, ULONG, PVOID, PSTR, ULONG)
_EXPORT(RtlMultiByteToUnicodeSize)
_EXPORT(RtlNtStatusToDosError)
_TRACE_(NTSTATUS, RtlPinAtomInAtomTable, 2, PVOID, USHORT)
_EXPORT(RtlQueryAtomInAtomTable)
_TRACE_(NTSTATUS, RtlQueryRegistryValues, 5, ULONG, PWSTR, PVOID, PVOID, PVOID)
_EXPORT(RtlRandom)
_EXPORT(RtlSetBits)
_TRACE_(NTSTATUS, RtlSetDaclSecurityDescriptor, 4, PVOID, BOOLEAN, PVOID, BOOLEAN)
_TRACE_(NTSTATUS, RtlSetGroupSecurityDescriptor, 3, PVOID, PVOID, BOOLEAN)
_TRACE_(NTSTATUS, RtlSetOwnerSecurityDescriptor, 3, PVOID, PVOID, BOOLEAN)
_TRACE_(NTSTATUS, RtlSetSaclSecurityDescriptor, 4, PVOID, BOOLEAN, PVOID, BOOLEAN)
_EXPORT(RtlSubAuthoritySid)
_EXPORT(RtlTimeToTimeFields)
_EXPORT(RtlUnicodeStringToAnsiString)
_TRACE_(NTSTATUS, RtlUnicodeStringToInteger, 3, PUNICODE_STRING, ULONG, PVOID)
_EXPORT(RtlUnicodeToCustomCPN)
_EXPORT(RtlUnicodeToMultiByteN)
_EXPORT(RtlUnicodeToMultiByteSize)
_EXPORT(RtlUnicodeToOemN)
_TRACE_(NTSTATUS, RtlUpcaseUnicodeString, 3, PUNICODE_STRING, PUNICODE_STRING, BOOLEAN)
_NOTRACE_(RtlWalkFrameChain)
_TRACE_(NTSTATUS, RtlWriteRegistryValue, 6, ULONG, PWSTR, PWSTR, ULONG, PVOID, ULONG)
_EXPORT(RtlZeroHeap)
_EXPORT(SeAssignSecurity)
_EXPORT(SeCaptureSecurityDescriptor)
_EXPORT(SeCaptureSubjectContext)
_EXPORT(SeCreateAccessState)
_EXPORT(SeCreateClientSecurity)
_EXPORT(SeDeassignSecurity)
_EXPORT(SeDeleteAccessState)
_EXPORT(SeImpersonateClientEx)
_EXPORT(SeLockSubjectContext)
_EXPORT(SePrivilegeCheck)
_EXPORT(SePrivilegeObjectAuditAlarm)
_TRACE_(NTSTATUS, SeQueryAuthenticationIdToken, 2, PVOID, PVOID)
_EXPORT(SeQueryInformationToken)
_EXPORT(SeReleaseSecurityDescriptor)
_EXPORT(SeReleaseSubjectContext)
_EXPORT(SeTokenIsRestricted)
_EXPORT(SeTokenType)
_EXPORT(SeUnlockSubjectContext)
_TRACE_(NTSTATUS, ZwAllocateVirtualMemory, 6, HANDLE, PVOID, SIZE_T, PVOID, ULONG, ULONG)
_EXPORT(ZwCancelIoFile)
_TRACE_(NTSTATUS, ZwClose, 1, HANDLE)
_TRACE_(NTSTATUS, ZwCreateDirectoryObject, 3, PVOID, ULONG, PVOID)
_TRACE_(NTSTATUS, ZwCreateEvent, 5, PVOID, ULONG, PVOID, ULONG, BOOLEAN)
_EXPORT(ZwCreateFile)
_TRACE_(NTSTATUS, ZwCreateKey, 7, PVOID, ULONG, PVOID, ULONG, PUNICODE_STRING, ULONG, PVOID)
_TRACE_(NTSTATUS, ZwCreateSection, 7, PVOID, ULONG, PVOID, PVOID, ULONG, ULONG, HANDLE)
_EXPORT(ZwDeleteFile)
_EXPORT(ZwDeleteKey)
_EXPORT(ZwDeviceIoControlFile)
_EXPORT(ZwDuplicateObject)
_EXPORT(ZwEnumerateKey)
_EXPORT(ZwEnumerateValueKey)
_TRACE_(NTSTATUS, ZwFreeVirtualMemory, 4, PVOID, PVOID, PVOID, ULONG)
//_TRACE_(NTSTATUS, ZwMapViewOfSection, 1, PVOID)
_NOTRACE_(ZwMapViewOfSection)
_EXPORT(ZwOpenDirectoryObject)
_EXPORT(ZwOpenEvent)
_EXPORT(ZwOpenFile)
_TRACE_(NTSTATUS, ZwOpenKey, 3, PVOID, ULONG, PVOID)
_EXPORT(ZwOpenProcessTokenEx)
_EXPORT(ZwOpenSymbolicLinkObject)
_EXPORT(ZwOpenThreadTokenEx)
_EXPORT(ZwPowerInformation)
_EXPORT(ZwQueryDefaultLocale)
_EXPORT(ZwQueryDefaultUILanguage)
_TRACE_(NTSTATUS, ZwQueryInformationFile, 5, PVOID, PVOID, PVOID, ULONG, ULONG)
_EXPORT(ZwQueryInformationProcess)
_EXPORT(ZwQueryInformationToken)
_NOTRACE_(ZwQueryKey) /// FIXME
_EXPORT(ZwQueryObject)
_EXPORT(ZwQuerySymbolicLinkObject)
_EXPORT(ZwQuerySystemInformation)
_TRACE_(NTSTATUS, ZwQueryValueKey, 6, PVOID, PUNICODE_STRING, ULONG, PVOID, ULONG, PVOID)
_TRACE_(NTSTATUS, ZwQueryVolumeInformationFile, 5, HANDLE, PVOID, PVOID, ULONG, ULONG)
_EXPORT(ZwReadFile)
_EXPORT(ZwSetDefaultLocale)
_EXPORT(ZwSetDefaultUILanguage)
_EXPORT(ZwSetEvent)
_EXPORT(ZwSetInformationFile)
_EXPORT(ZwSetInformationThread)
_EXPORT(ZwSetSecurityObject)
_TRACE_(NTSTATUS, ZwSetSystemInformation, 3, ULONG, PVOID, SIZE_T)
_NOTRACE_(ZwSetValueKey) /// FIXME
_EXPORT(ZwTerminateProcess)
_EXPORT(ZwUnmapViewOfSection)
_EXPORT(ZwYieldExecution)
_EXPORT(sprintf)
_NOTRACE_(vDbgPrintEx)
_NOTRACE_(_alldiv)
_NOTRACE_(_alldvrm)
_NOTRACE_(_allmul)
_NOTRACE_(_allshr)
_NOTRACE_(_aulldiv)
_NOTRACE_(_aulldvrm)
_NOTRACE_(_except_handler3)
_NOTRACE_(_strnicmp)
_NOTRACE_(_wcsicmp)
_NOTRACE_(_wcsnicmp)
_NOTRACE_(memmove)
_NOTRACE_(qsort)
_NOTRACE_(strchr)
_NOTRACE_(strncmp)
_NOTRACE_(strncpy)
_NOTRACE_(swprintf)
_NOTRACE_(toupper)
_NOTRACE_(vsprintf)
_NOTRACE_(wcscat)
_NOTRACE_(wcschr)
_NOTRACE_(wcscmp)
_NOTRACE_(wcscpy)
_NOTRACE_(wcslen)
_NOTRACE_(wcsncmp)
_NOTRACE_(wcsncpy)
_NOTRACE_(wcsrchr)
_NOTRACE_(wcsstr)
_NOTRACE_(_vsnprintf)
