1 stdcall -noname QueryThemeServices()
2 stdcall -noname OpenThemeFile()
3 stdcall -noname CloseThemeFile()
4 stdcall -noname ApplyTheme()
5 stdcall CloseThemeData()
6 stdcall DrawThemeBackground()
7 stdcall -noname GetThemeDefaults()
8 stdcall -noname EnumThemes()
9 stdcall -noname EnumThemeColors()
10 stdcall -noname EnumThemeSizes()
11 stdcall -noname ParseThemeIniFile()
12 stdcall DrawThemeEdge()
13 stdcall -noname DrawNCPreview()
14 stdcall -noname RegisterDefaultTheme()
15 stdcall -noname DumpLoadedThemeToTextFile()
16 stdcall -noname OpenThemeDataFromFile()
17 stdcall -noname OpenThemeFileFromData()
18 stdcall -noname GetThemeSysSize96()
19 stdcall -noname GetThemeSysFont96()
20 stdcall -noname SessionAllocate()
21 stdcall -noname SessionFree()
22 stdcall -noname ThemeHooksOn()
23 stdcall -noname ThemeHooksOff()
24 stdcall -noname AreThemeHooksActive()
25 stdcall -noname GetCurrentChangeNumber()
26 stdcall -noname GetNewChangeNumber()
27 stdcall -noname SetGlobalTheme()
28 stdcall -noname GetGlobalTheme()
29 stdcall -noname CheckThemeSignature()
30 stdcall -noname LoadTheme()
31 stdcall -noname InitUserTheme()
32 stdcall -noname InitUserRegistry()
33 stdcall -noname ReestablishServerConnection()
34 stdcall -noname ThemeHooksInstall()
35 stdcall -noname ThemeHooksRemove()
36 stdcall -noname RefreshThemeForTS()
37 stdcall DrawThemeIcon()
38 stdcall DrawThemeParentBackground()
39 stdcall DrawThemeText()
40 stdcall EnableThemeDialogTexture()
41 stdcall EnableTheming()
42 stdcall GetCurrentThemeName()
43 stdcall -noname ClassicGetSystemMetrics()
44 stdcall -noname ClassicSystemParametersInfoA()
45 stdcall -noname ClassicSystemParametersInfoW()
46 stdcall -noname ClassicAdjustWindowRectEx()
47 stdcall DrawThemeBackgroundEx()
48 stdcall -noname GetThemeParseErrorInfo()
49 stdcall GetThemeAppProperties()
50 stdcall GetThemeBackgroundContentRect()
51 stdcall GetThemeBackgroundExtent()
52 stdcall GetThemeBackgroundRegion()
53 stdcall GetThemeBool()
54 stdcall GetThemeColor()
55 stdcall GetThemeDocumentationProperty()
56 stdcall GetThemeEnumValue()
57 stdcall GetThemeFilename()
58 stdcall GetThemeFont()
59 stdcall GetThemeInt()
60 stdcall -noname CreateThemeDataFromObjects()
61 stdcall -noname OpenThemeDataEx()
62 stdcall -noname ServerClearStockObjects()
63 stdcall -noname MarkSection()
64 stdcall -noname ProcessLoadTheme_RunDLLW()
65 stdcall -noname SetSystemVisualStyle()
66 stdcall -noname ServiceClearStockObjects()
67 stdcall GetThemeIntList()
68 stdcall GetThemeMargins()
69 stdcall GetThemeMetric()
70 stdcall GetThemePartSize()
71 stdcall GetThemePosition()
72 stdcall GetThemePropertyOrigin()
73 stdcall -noname IsThemeActiveByPolicy()
74 stdcall GetThemeRect()
75 stdcall GetThemeString()
76 stdcall GetThemeSysBool()
77 stdcall GetThemeSysColor()
78 stdcall GetThemeSysColorBrush()
79 stdcall GetThemeSysFont()
80 stdcall GetThemeSysInt()
81 stdcall GetThemeSysSize()
82 stdcall GetThemeSysString()
83 stdcall GetThemeTextExtent()
84 stdcall GetThemeTextMetrics()
85 stdcall GetWindowTheme()
86 stdcall HitTestThemeBackground()
87 stdcall IsAppThemed()
88 stdcall IsThemeActive()
89 stdcall IsThemeBackgroundPartiallyTransparent()
90 stdcall IsThemeDialogTextureEnabled()
91 stdcall IsThemePartDefined()
92 stdcall OpenThemeData()
93 stdcall SetThemeAppProperties()
94 stdcall SetWindowTheme()
95 stdcall ThemeInitApiHook()
