1 stdcall -noname QueryThemeServices()
2 stdcall -noname RETIRED_OpenThemeFile() SHUNIMPL.#440
3 stdcall -noname RETIRED_CloseThemeFile() SHUNIMPL.#441
4 stdcall -noname RETIRED_ApplyTheme() SHUNIMPL.#445
5 stdcall BeginPanningFeedback(ptr)
6 stdcall EndPanningFeedback(ptr long)
7 stdcall -noname GetThemeDefaults(wstr wstr long wstr long)
8 stdcall -noname EnumThemes(wstr ptr double)
9 stdcall -noname EnumThemeColors(wstr wstr long ptr)
10 stdcall -noname EnumThemeSizes(wstr wstr long ptr)
11 stdcall -noname RETIRED_ParseThemeIniFile() SHUNIMPL.#190
12 stdcall UpdatePanningFeedback(ptr long long long)
13 stdcall -noname RETIRED_DrawNCPreview() SHUNIMPL.#444
14 stdcall -noname RegisterDefaultTheme(wstr long)
15 stdcall -noname DumpLoadedThemeToTextFile(ptr wstr long long)
16 stdcall -noname OpenThemeDataFromFile(ptr ptr wstr long)
17 stdcall -noname OpenThemeFileFromData(ptr ptr)
18 stdcall -noname RETIRED_GetThemeSysSize96() SHUNIMPL.#189
19 stdcall -noname RETIRED_GetThemeSysFont96() SHUNIMPL.#188
20 stdcall -noname RETIRED_Service_SessionAllocate() SHUNIMPL.#395
21 stdcall -noname RETIRED_Service_SessionFree() SHUNIMPL.#396
22 stdcall -noname RETIRED_Service_ThemeHooksOn() SHUNIMPL.#397
23 stdcall -noname RETIRED_Service_ThemeHooksOff() SHUNIMPL.#398
24 stdcall -noname RETIRED_Service_AreThemeHooksActive() SHUNIMPL.#399
25 stdcall -noname RETIRED_Service_GetCurrentChangeNumber() SHUNIMPL.#400
26 stdcall -noname RETIRED_GetNewChangeNumber() SHUNIMPL.#215
27 stdcall -noname RETIRED_Service_SetGlobalTheme() SHUNIMPL.#401
28 stdcall -noname RETIRED_Service_GetGlobalTheme() SHUNIMPL.#402
29 stdcall -noname RETIRED_CheckThemeSignature() SHUNIMPL.#213
30 stdcall -noname RETIRED_Service_CopyTheme() SHUNIMPL.#403
31 stdcall -noname RETIRED_Remote_InitUserTheme() SHUNIMPL.#431
32 stdcall -noname RETIRED_Remote_InitUserRegistry() SHUNIMPL.#406
33 stdcall -noname Remote_ReestablishServerConnection()
34 stdcall -noname RETIRED_Remote_ThemeHooksInstall() SHUNIMPL.#407
35 stdcall -noname RETIRED_Remote_ThemeHooksRemove() SHUNIMPL.#408
36 stdcall -noname RefreshThemeForTS()
37 stdcall BeginBufferedAnimation(ptr ptr ptr long ptr ptr ptr ptr)
38 stdcall BeginBufferedPaint(ptr ptr long ptr ptr)
39 stdcall BufferedPaintClear(ptr ptr)
40 stdcall BufferedPaintInit()
41 stdcall BufferedPaintRenderAnimation(ptr ptr)
42 stdcall BufferedPaintSetAlpha(ptr ptr long)
43 stdcall -noname ClassicGetSystemMetrics(long)
44 stdcall -noname ClassicSystemParametersInfoA(long long ptr long)
45 stdcall -noname ClassicSystemParametersInfoW(long long ptr long)
46 stdcall -noname ClassicAdjustWindowRectEx(ptr long long long)
47 stdcall DrawThemeBackgroundEx(ptr ptr long long ptr ptr)
48 stdcall -noname GetThemeParseErrorInfo(ptr)
49 stdcall -noname OpenNcThemeData(ptr wstr)
50 stdcall -noname IsThemeClassDefined(ptr wstr wstr long)
51 stdcall BufferedPaintStopAllAnimations(ptr)
52 stdcall BufferedPaintUnInit()
53 stdcall CloseThemeData(ptr)
54 stdcall DllCanUnloadNow()
55 stdcall DllGetActivationFactory(ptr ptr)
56 stdcall DllGetClassObject(ptr ptr ptr)
57 stdcall DrawThemeBackground(ptr ptr long long ptr ptr)
58 stdcall DrawThemeEdge(ptr ptr long long ptr long long ptr)
59 stdcall DrawThemeIcon(ptr ptr long long ptr ptr long)
60 stdcall -noname CreateThemeDataFromObjects(ptr ptr long)
61 stdcall OpenThemeDataEx(ptr wstr long)
62 stdcall -noname RETIRED_Remote_ClearStockObjects() SHUNIMPL.#409
63 stdcall -noname RETIRED_Service_MarkSection() SHUNIMPL.#404
64 stdcall -noname Process_LoadTheme_RunDLLW(ptr ptr wstr long)
65 stdcall -noname SetSystemVisualStyle(wstr wstr wstr long)
66 stdcall -noname RETIRED_Service_ClearStockObjects() SHUNIMPL.#405
67 stdcall -noname AddThemeAppCompatFlags(long long)
68 stdcall -noname ResetThemeAppCompatFlags()
69 stdcall -noname EnumThemeProperties(ptr)
70 stdcall DrawThemeParentBackground(ptr ptr ptr)
71 stdcall DrawThemeParentBackgroundEx(ptr ptr long ptr)
72 stdcall -noname DrawThemeIconEx(ptr ptr long long ptr ptr long ptr)
73 stdcall -noname IsThemeActiveByPolicy()
74 stdcall -noname GetThemeClass(ptr wstr long)
75 stdcall -noname ThemeForwardCapturedMouseMessage(ptr long double double)
76 stdcall -noname EnableServiceConnection(long)
77 stdcall -noname RETIRED_LoadTheme() SHUNIMPL.#432
78 stdcall -noname RETIRED_ThemeSection_Open() SHUNIMPL.#433
79 stdcall -noname RETIRED_ThemeSection_Close() SHUNIMPL.#434
80 stdcall -noname RETIRED_ThemeSection_ValidateData() SHUNIMPL.#435
81 stdcall -noname RETIRED_ThemeSection_CreateFromSection() SHUNIMPL.#430
82 stdcall -noname RETIRED_ThemeSection_Get() SHUNIMPL.#436
83 stdcall -noname RETIRED_ThemeSection_GetData() SHUNIMPL.#437
84 stdcall -noname ClearTheme(ptr ptr long)
85 stdcall -noname ClassicWndProc(ptr ptr long double double ptr)
86 stdcall -noname IsValidShakeWindow(ptr)
87 stdcall -noname RETIRED_InitUserTheme() SHUNIMPL.#438
88 stdcall -noname RETIRED_LoadUserTheme() SHUNIMPL.#439
89 stdcall DrawThemeText(ptr ptr long long wstr long long long ptr)
90 stdcall -noname SetSystemMetrics(ptr long)
91 stdcall -noname SendAcquireOrAddTheme(wstr wstr wstr long long ptr ptr ptr)
92 stdcall -noname LoaderLoadTheme(ptr ptr wstr wstr wstr ptr wstr long ptr wstr long ptr ptr long long long)
93 stdcall -noname ApplyThemeSections(ptr wstr wstr long long)
94 stdcall -noname GetColorPreferencePresetCount()
95 stdcall GetImmersiveColorFromColorSetEx(long long long long)
96 stdcall -noname GetImmersiveColorTypeFromName(wstr)
97 stdcall -noname SetImmersiveUserColorSetPreferenceEx(long long)
98 stdcall GetImmersiveUserColorSetPreference(long long)
99 stdcall -noname InitializeImmersiveColorSetSharedMemory()
100 stdcall -noname GetImmersiveColorNamedTypeByIndex(long)
101 stdcall -noname SetImmersiveColorSetSharedMemoryACLforUser(wstr)
102 stdcall -noname SetImmersiveColorSetInSharedMemory(long)
103 stdcall -noname HueShiftPalettizedPNG(ptr long long long)
104 stdcall -noname RefreshImmersiveColorPolicyState()
105 stdcall -noname GetImmersiveDefaultColorSet()
106 stdcall -noname GetIsImmersiveColorUsingHighContrast(long)
107 stdcall -noname GetCustomColorSet(wstr ptr)
108 stdcall -noname GetCustomAccentPath(long wstr long)
109 stdcall -noname GetIsImmersiveExpression(wstr)
110 stdcall -noname AnimationDescription::InternalGetTrustLevel()
111 stdcall -noname GetCurrentExpressionId(wstr long)
112 stdcall -noname GetCustomAccentTopRatio(ptr)
113 stdcall -noname GetCustomAccentLoadStatus(wstr ptr)
114 stdcall DrawThemeTextEx(ptr ptr long long wstr long long ptr ptr)
115 stdcall -noname InvalidateAppTheme()
116 stdcall -noname SendReleaseTheme(wstr)
117 stdcall -noname GetColorPreferencePresetCount()
118 stdcall -noname GetColorPreferencePreset(ptr long)
119 stdcall -noname GetDefaultColorPreference(ptr)
120 stdcall GetUserColorPreference(ptr long)
121 stdcall GetColorFromPreference(ptr long long long)
122 stdcall -noname SetUserColorPreference(ptr long)
123 stdcall -noname SetImmersiveColorPreferenceInSharedMemory(ptr)
124 stdcall -noname GetImmersiveColorXamlInfoByIndex(long)
125 stdcall -noname GetGroupPolicyColors(ptr ptr)
126 stdcall -noname DrawTextWithGlow(ptr wstr long ptr long long long long long long ptr double)
127 stdcall -noname LoaderLoadThemeForTesting(ptr)
128 stdcall -noname ClearDpiInfo()
129 stdcall -noname OpenThemeDataForDPI(ptr wstr long)
130 stdcall EnableThemeDialogTexture(ptr long)
131 stdcall EnableTheming()
132 stdcall EndBufferedAnimation(ptr long)
133 stdcall EndBufferedPaint(ptr long)
134 stdcall GetBufferedPaintBits(ptr ptr ptr)
135 stdcall GetBufferedPaintDC(ptr)
136 stdcall GetBufferedPaintTargetDC(ptr)
137 stdcall GetBufferedPaintTargetRect(ptr ptr)
138 stdcall GetCurrentThemeName(wstr long wstr long wstr long)
139 stdcall GetThemeAnimationProperty(ptr long long long ptr long ptr)
140 stdcall GetThemeAnimationTransform(ptr long long long ptr long ptr)
141 stdcall GetThemeAppProperties()
142 stdcall GetThemeBackgroundContentRect(ptr ptr long long ptr ptr)
143 stdcall GetThemeBackgroundExtent(ptr ptr long long ptr ptr)
144 stdcall GetThemeBackgroundRegion(ptr ptr long long ptr ptr)
145 stdcall GetThemeBitmap(ptr long long long long ptr)
146 stdcall GetThemeBool(ptr long long long ptr)
147 stdcall GetThemeColor(ptr long long long ptr)
148 stdcall GetThemeDocumentationProperty(wstr wstr wstr long)
149 stdcall GetThemeEnumValue(ptr long long long ptr)
150 stdcall GetThemeFilename(ptr long long long wstr long)
151 stdcall GetThemeFont(ptr ptr long long long ptr)
152 stdcall GetThemeInt(ptr long long long ptr)
153 stdcall GetThemeIntList(ptr long long long ptr)
154 stdcall GetThemeMargins(ptr ptr long long long ptr ptr)
155 stdcall GetThemeMetric(ptr ptr long long long ptr)
156 stdcall GetThemePartSize(ptr ptr long long ptr long ptr)
157 stdcall GetThemePosition(ptr long long long ptr)
158 stdcall GetThemePropertyOrigin(ptr long long long ptr)
159 stdcall GetThemeRect(ptr long long long ptr)
160 stdcall GetThemeStream(ptr long long long ptr ptr ptr)
161 stdcall GetThemeString(ptr long long long wstr long)
162 stdcall GetThemeSysBool(ptr long)
163 stdcall GetThemeSysColor(ptr long)
164 stdcall GetThemeSysColorBrush(ptr long)
165 stdcall GetThemeSysFont(ptr long ptr)
166 stdcall GetThemeSysInt(ptr long ptr)
167 stdcall GetThemeSysSize(ptr long)
168 stdcall GetThemeSysString(ptr long wstr long)
169 stdcall GetThemeTextExtent(ptr ptr long long wstr long long ptr ptr)
170 stdcall GetThemeTextMetrics(ptr ptr long long ptr)
171 stdcall GetThemeTimingFunction(ptr long ptr long ptr)
172 stdcall GetThemeTransitionDuration(ptr long long long long ptr)
173 stdcall GetWindowTheme(ptr)
174 stdcall HitTestThemeBackground(ptr ptr long long long ptr ptr double ptr)
175 stdcall IsAppThemed()
176 stdcall IsCompositionActive()
177 stdcall IsThemeActive()
178 stdcall IsThemeBackgroundPartiallyTransparent(ptr long long)
179 stdcall IsThemeDialogTextureEnabled(ptr)
180 stdcall IsThemePartDefined(ptr long long)
181 stdcall OpenThemeData(ptr wstr)
182 stdcall SetThemeAppProperties(long)
183 stdcall SetWindowTheme(ptr wstr wstr)
184 stdcall SetWindowThemeAttribute(ptr long ptr long)
185 stdcall ThemeInitApiHook(long ptr)
